.storybook/config.js
.storybook/whitepaperStorybookTheme.js
src/components/Button/Button.css
src/components/Button/Button.stories.jsx
src/components/Button/index.tsx
src/components/ChoiceGroup/styles.css
src/components/Common/Common.stories.jsx
src/components/Common/styles.css
src/storybook-features/Linking.stories.jsx
src/themes/theme_control_gpn-dark.css
src/themes/theme_control_gpn-default.css
yarn.lock

- Добавляет модификаторы only-icon и with-icon для Button.
- Правит тему сторибука для лучшего переключения тем.
- Добавляет ховер для ChoiceGroup
- Мелкие правки

New features

---

.travis.yml
package.json
src/components/index.ts

Добавил экспорт компонента Switch. Удалил автопатч версии пакета, т.к. он некорректно работает и версия обновляется ручками

update travis config, version, export switch

---

src/components/Checkbox/styles.css

Добавил flex-shrink: 0 к полю чекбокса во избежание таких случаев:

checkbox flex fix

---

src/components/Button/Button.stories.jsx
src/components/Button/index.tsx

Добавил пропс `url`, который позволяет использовать `Button` в качестве тега ссылки `<a>`.

Добавлена возможность использовать Button в качестве ссылки

---

src/components/Button/Button.css
src/components/Button/Button.tsx
src/components/TextField/TextField.css
src/components/TextField/TextField.stories.tsx
src/components/TextField/TextField.tsx

Потестила на прототипе — вот то, что нужно было пофиксить

[fix] Button and TextField

---

package.json
src/components/Badge/Badge.stories.tsx
src/components/Badge/index.tsx
src/components/Badge/styles.css

- Чуваки из CSSSR попросили обновить бейдж в текущей реализации в соответсвии с макетами
- Добавил размер L
- Поправил минифицированный вид

[Feature] Badge — add L size to Master

---

src/components/Badge/Badge.css
src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx

добавил новый размер для Бейджа
поправил вид минифицированных в соответсвии с фигмой

[Feature] Badge — add L size to Dev

---

src/components/Button/Button.css
src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx
src/components/Loader/Loader.css
src/components/Loader/Loader.tsx

feat(Button, Loader): добавил состояние loading для кнопки

---

src/components/Header/Header.tsx

В **Header** не экспортируется **HeaderModule**

Add missed HeaderModule export

---

src/components/Button/Button.test.tsx

добавил генерация стилей с помощью `cnButton`
подправил тест "должен рендериться как функциональный компонент"

Подправил тесты

---

build.config.js

#102 
Убрал из исключений в пакет
Input
Select
Popover
Textarea
в реэкспорт они все равно не попадают, так как структура не по БЭМ

Убрал из исключений в пакет старые компоненты

---

build.config.js
src/components/Checkbox/Checkbox.css
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Radio/Radio.tsx
src/components/Switch/Switch.stories.tsx
src/components/Switch/Switch.tsx

Поменял в компонентах onChange на нативный:
Checkbox.tsx
Radio.tsx
Switch.tsx

Поменял onChange на нативный

---

src/components/Avatar/Avatar.css
src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/Avatar.tsx

feat(Avatar): добавил отображение инициалов и цветов

---

src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/Avatar.test.tsx
src/components/Avatar/Avatar.tsx

Дополнительно заменил конструкцию с setProperty на инлайновый стиль

Написать тесты для компонента Avatar

---

src/components/BaseCheckGroupField/BaseCheckGroupField.stories.tsx_
src/components/BaseCheckGroupField/BaseCheckGroupField.tsx
src/components/ChoiceGroup/ChoiceGroup.stories.tsx
src/components/ChoiceGroup/Item/ChoiceGroup__item.tsx
src/components/Tabs/Tabs.tsx

Переименовал multiply на multiple

Переименовал multiply на multiple

---

src/components/Checkbox/Checkbox.tsx
src/components/Radio/Radio.tsx
src/components/Switch/Switch.tsx
src/utils/types/PropsWithHTMLAttributes.ts

Исправил в компонентах onChandge, и добавил forwardRef

Исправил Checkbox Radio Swith

---

README.md

docs(readme): theme connection

---

src/components/BaseCheckGroupField/BaseCheckGroupField.tsx

fix(BaseCheckGroupField): fix getChecked

---

src/components/Attach/Attach.tsx
src/components/Attach/stories/Attach.mdx
src/components/Badge/Badge.md
src/components/Badge/Badge.tsx
src/components/Button/Button.tsx
src/components/ChoiceGroup/ChoiceGroup.stories.tsx
src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/ChoiceGroup/Item/ChoiceGroup__item.tsx
src/components/File/File.tsx
src/components/Header/Menu/Header-Menu.tsx
src/components/Informer/Informer.tsx
src/components/SnackBar/SnackBar.md
src/components/SnackBar/SnackBar.tsx
src/components/SnackBar/stories/SnackBar.stories.tsx
src/components/Tabs/Tab/Tabs-Tab.tsx
src/components/Tabs/Tabs.md
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/Tabs.tsx
src/components/TextField/TextField.tsx
src/fileIcons/BaseFileIconHoc/BaseFileIconHoc.tsx
src/fileIcons/FileIcon/FileIcon.tsx
src/fileIcons/FileIcon/stories/Item/Icons-Item.tsx
src/icons/BaseIconHoc/BaseIconHoc.tsx
src/icons/Icon/Icon.tsx
src/icons/Icon/stories/Item/Icons-Item.tsx

BREAKING CHANGE:
rename types IIcon -> IconProps, IFileIcon -> FileIconProps, IFile -> FileProps
closes #211

fix(global): rename types

---

builder/helpers.js
builder/templates/FileIcons.stories.tsx.template
builder/templates/Icons.stories.tsx.template
src/fileIcons/FileIcon/stories/FileIcons.stories.tsx
src/icons/Icon/stories/Icons.stories.tsx

closes  #206
Сортировка иконок в сторибуке

feat(Icons): sort icons in storyBook

---

src/components/TextField/TextField.css

fix(TextField): fix color icons

---

package.json
yarn.lock

issue -  #205
обновил tslib до версии 13.0.0

chore(tslib): update -> 13.0.0

---

src/components/Theme/Theme.tsx

closes #222
Добавил ref в Theme

feat(Theme): add ref

---

src/icons/IconAlignRight/IconAlignRight_size_m.svg
src/icons/IconAlignRight/IconAlignRight_size_m.tsx
src/icons/IconAlignRight/IconAlignRight_size_s.svg
src/icons/IconAlignRight/IconAlignRight_size_s.tsx
src/icons/IconAlignRight/IconAlignRight_size_xs.svg
src/icons/IconAlignRight/IconAlignRight_size_xs.tsx

fix(iconAlignRight): replace wrong svg

---

src/components/FileField/FileField.css
src/components/FileField/FileField.tsx
src/components/FileField/__stories__/FileField.mdx
src/components/FileField/__stories__/FileField.stories.css
src/components/FileField/__stories__/FileField.stories.tsx
src/components/FileField/__stories__/cn.ts
src/components/FileField/__stories__/examples/ExampleValueInterception/ExampleValueInterception.css
src/components/FileField/__stories__/examples/ExampleValueInterception/ExampleValueInterception.tsx
src/components/FileField/__tests__/FileField.test.tsx

closes #157
Новый компонент FileFileld

feat(FileField): add component FileField

---

src/components/Switch/Switch.css
src/components/Switch/Switch.tsx
src/components/Switch/__stories__/Switch.stories.tsx

Feature/switch add S size

---

src/components/TextField/TextField.tsx

BREAKING CHANGE:
component api change
closes  #242
Исправлены типы у `onFocus` и `onBlur`

fix(TextField): change type onFocus and onBlur

---

src/components/Theme/__stories__/examples/ThemeExampleRoot/ThemeExampleRoot.tsx

closes -  #286
исправил ошибку, не верное имя компонента

fix(ThemeDocs): fix runtime error

---

src/components/Table/Table.tsx

closes #309
Поправил условие, когда мы используем ресайз и прилипание колонок

fix(Table): change condition for initial column widths

---

src/utils/types/PropsWithHTMLAttributes.ts

fix(Types): emotions affect types

---

src/components/Button/Button.css

fix(Button): remove z-index

---

src/components/ProgressSpin/__stories__/ProgressSpin.mdx
yarn.lock

Docs/Progress Spin

---

src/uiKit/components/DocsExample/DocsExample.tsx

closes -  #294
не было импорта стилей

fix(Docs): fix DocsExample styles

---

.github/CODEOWNERS

добавлена @arhayka для просмотра документации

chore(CODEOWNERS): add @arhayka

---

src/components/Attach/Attach.css
src/components/Attach/Attach.tsx

closes -  #312
Добавленна возможность задать `onButtonClick` без указания `OnClick`

fix(Attach): fix onButtonClick

---

src/utils/types/PropsWithHTMLAttributes.ts

fix(Types): added remove "css" types from attributes

---

src/components/Avatar/__stories__/Avatar.mdx
src/components/Avatar/__stories__/examples/AvatarExampleForm/AvatarExampleForm.tsx
src/components/Avatar/__stories__/examples/AvatarExampleImage/AvatarExampleImage.tsx
src/components/Avatar/__stories__/examples/AvatarExampleSize/AvatarExampleSize.tsx

Docs(Avatar): add docs for Avatar

---

src/components/ChoiceGroup/ChoiceGroup.css

fix(ChoiceGroup): fix view secondary

---

src/components/FileField/__stories__/FileField.mdx
src/components/FileField/__stories__/examples/FileFieldExampleRenderProp/FileFieldExampleRenderProp.tsx
src/components/FileField/__stories__/examples/FileFieldExampleWithoutRenderProp/FileFieldExampleWithoutRenderProp.tsx

docs(FileField): edit docs for FileField

---

CHANGELOG.md
README.md
package.json
src/components/Attach/__stories__/Attach.mdx
src/components/Avatar/__stories__/Avatar.mdx
src/components/Badge/__stories__/Badge.mdx
src/components/BasicSelect/__stories__/BasicSelect.mdx
src/components/Button/__stories__/Button.mdx
src/components/Checkbox/__stories__/Checkbox.mdx
src/components/ChoiceGroup/__stories__/ChoiceGroup.mdx
src/components/File/__stories__/File.mdx
src/components/FileField/__stories__/FileField.mdx
src/components/Informer/__stories__/Informer.mdx
src/components/Loader/__stories__/Loader.mdx
src/components/ProgressSpin/__stories__/ProgressSpin.mdx
src/components/Radio/__stories__/Radio.mdx
src/components/SnackBar/__stories__/SnackBar.mdx
src/components/Switch/__stories__/Switch.mdx
src/components/Table/__stories__/Table.mdx
src/components/Tabs/__stories__/Tabs.mdx
src/components/Tag/__stories__/Tag.mdx
src/components/Text/__stories__/Text.mdx
src/components/TextField/__stories__/TextField.mdx
src/components/Theme/__stories__/Theme.mdx
src/components/Timer/__stories__/Timer.mdx
src/components/User/__stories__/User.mdx

chore(repository): moving to gazprom-neft/consta-uikit

---

.storybook/main.js

closes #377
исправил конфиг сборки storybook так чтоб собирался под windows

chore(Storybook configs): fix storybook build on windows

---

src/components/ChoiceGroup/__stories__/ChoiceGroup.mdx

fix(ChoiceGroup): fix import in doc example

---

src/components/Popover/Popover.tsx
src/components/Popover/__tests__/helpers.test.ts
src/components/Popover/helpers.ts
src/components/Tooltip/Tooltip.css

closes -  #297
добавил новые позиции для Popover иTooltip

feat(Popover): add new positions

---

src/utils/whitepaper/whitepaper.css

fix(whitepaper): whitepaper affected documentation styles, fixed text weight

---

docs/common/about.mdx
docs/common/developers/commits-style.mdx
docs/common/developers/contributors.mdx
docs/common/developers/file-structure/file-structure-components.mdx
docs/common/developers/file-structure/file-structure.mdx
docs/common/developers/review.mdx
docs/common/start.mdx

closes  #383
Добавлена документация подключения дизайн системы

docs(start): add docs start

---

src/components/TextField/TextField.css
src/components/TextField/TextField.tsx

fix(TextField): fix sides styles

---

.github/CODEOWNERS

chore(CODEOWNERS): add @c1n1k

---

builder/build.js
builder/helpers.js
package.json

add README.md, CHANGELOG.md to build. Add keywords to package.json
closes #276

chore(builder): add README.md, CHANGELOG.md to build

---

src/components/Informer/Informer.tsx
src/components/Informer/__tests__/Informer.test.tsx

test(Informer): add test

---

src/components/Loader/__tests__/Loader.test.tsx

test(Loader): add tests

---

src/components/MultiCombobox/MultiCombobox.tsx
src/components/MultiCombobox/__stories__/MultiCombobox.stories.tsx
src/components/SelectComponents/Select.css
src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx

* removed xs size
* fixed popover direction
* fixed input size
issue - #438 #451 #452
* убрал размер xs
* исправил позицию поповера
* исправил вычисление ширины инпута

fix(MultiCombobox): several bugs fixed

---

src/components/Sidebar/Sidebar.css
src/components/Sidebar/Sidebar.tsx
src/components/Sidebar/__stories__/Sidebar.mdx
src/components/Sidebar/__stories__/Sidebar.stories.css
src/components/Sidebar/__stories__/Sidebar.stories.tsx
src/components/Sidebar/__tests__/Sidebar.test.tsx

Pr to consta sidebar

---

src/components/BasicSelect/BasicSelect.tsx
src/components/Combobox/Combobox.tsx
src/components/MultiCombobox/MultiCombobox.tsx

Исправлена проблема с обновлением значения в селектах в случаях когда изменение значения зависело от «третьих» функций или происходило в хуке. https://gaz-vega.slack.com/archives/C012N8C831S/p1601301225002700?thread_ts=1601300434.002400&cid=C012N8C831S

Исправить обновление значение селекта

---

src/components/Header/Header.css

Бэкграунд не установлен - в итоге в тёмной теме вижу белый фон.
До фикса:
После фикса:

fix(Header): fixed dark theme background

---

src/components/TextField/TextField.tsx
src/components/TextField/__tests__/TextField.test.tsx

test(TextField): added tests

---

src/components/User/User.tsx
src/components/User/__tests__/User.test.tsx

test(User): added tests

---

src/components/Table/Cell/TableCell.css

issue -  #466
hyphens: auto - не работает
оставил только overflow-wrap: break-word;

fix(Table): hyphenation, words were not carried over

---

src/components/Badge/__tests__/Badge.test.tsx

test(Badge): added tests

---

builder/templates/FileIconsGallery.tsx.template
src/components/File/File.tsx
src/components/File/__stories__/File.stories.tsx
src/components/File/__tests__/File.test.tsx
src/fileIcons/FileIcon/FileIcon.tsx
src/fileIcons/FileIcon/__stories__/FileIconsGallery/FileIconsGallery.tsx

test(File): add tests

---

src/components/ChoiceGroup/__tests__/ChoiceGroup.test.tsx
src/components/TextField/__tests__/TextField.test.tsx

issue -  #463
Добавил тесты onChange

test(ChoiceGroup): added new tests

---

src/components/SelectComponents/Select.css

feat(selects): added cursor: pounter for list items

---

src/components/Table/Table.tsx

even and odd lines were mixed up
issue -  #491

fix(Table): fixed zebraStriped

---

src/components/Radio/__tests__/Radio.test.tsx

test(Radio): added tests

---

src/components/ProgressSpin/__tests__/ProgressSpin.test.tsx

test(ProgressSpin): added tests

---

src/components/PortalWithTheme/__tests__/PortalWithTheme.test.tsx
src/components/Theme/Theme.tsx

test(PortalWithTheme): added tests

---

src/components/Switch/__tests__/Switch.test.tsx

test(Switch): added tests

---

src/components/Text/__tests__/Text.test.tsx

test(Text): added tests

---

src/components/Header/Header.css
src/components/Timer/Timer.tsx
src/components/Timer/__tests__/Timer.test.tsx

test(Timer): added tests

---

src/icons/IconTrash/IconTrash.tsx
src/icons/IconTrash/IconTrash_size_xs.svg
src/icons/IconTrash/IconTrash_size_xs.tsx

feat(Icons): add IconTrash-xs

---

src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx

issue -  #500
исправлена не уникальность ключей в дропдауне

fix(Combobox): fixed non-uniqueness of keys in dropdown

---

src/components/Theme/Theme.tsx
src/components/Theme/__tests__/Theme.test.tsx

test(Theme): added tests

---

src/components/Checkbox/__tests__/Checkbox.test.tsx

test(Checkbox): added tests

---

src/icons/Icon/__stories__/Icons.stories.tsx
src/icons/IconWatch/IconWatch.tsx
src/icons/IconWatch/IconWatch_size_m.svg
src/icons/IconWatch/IconWatch_size_m.tsx
src/icons/IconWatch/IconWatch_size_s.svg
src/icons/IconWatch/IconWatch_size_s.tsx
src/icons/IconWatch/IconWatch_size_xs.svg
src/icons/IconWatch/IconWatch_size_xs.tsx

feat(Icons): add IconWatch

---

src/components/Informer/Informer.css

добавить фон для информера в модификации bordered

---

src/components/Checkbox/Checkbox.css
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__stories__/Checkbox.mdx
src/components/Checkbox/__stories__/Checkbox.stories.tsx
src/components/Checkbox/__stories__/examples/CheckboxExampleAlign/CheckboxExampleAlign.tsx
src/components/Radio/Radio.css
src/components/Radio/Radio.tsx
src/components/Radio/__stories__/Radio.mdx
src/components/Radio/__stories__/Radio.stories.tsx
src/components/Radio/__stories__/examples/RadioExampleAlign/RadioExampleAlign.tsx
src/components/Switch/Switch.css
src/components/Switch/Switch.tsx
src/components/Switch/__stories__/Switch.mdx
src/components/Switch/__stories__/Switch.stories.tsx
src/components/Switch/__stories__/examples/SwitchExampleAlign/SwitchExampleAlign.tsx

feat(Checkbox, Radio, Switch): added alignment modifier

---

src/components/ChoiceGroup/ChoiceGroup.css

closes #540
Исправлена высота компонента в соответствии с размерной сеткой.
Исправлены скругления разделителей во view_ghost + form_round согласно дизайну.

fix(Choicegroup): fix control height and dividers border-radius

---

src/icons/Icon/__stories__/Icons.stories.tsx
src/icons/IconWideScreen/IconWideScreen.tsx
src/icons/IconWideScreen/IconWideScreen_size_xs.svg
src/icons/IconWideScreen/IconWideScreen_size_xs.tsx

feat(iconwidescreen): added icons

---

src/components/Table/Table.tsx
src/components/Table/__stories__/Table.stories.tsx

feat(Table): added onRowHover props

---

src/components/Modal/Modal.tsx

Пофикшен баг отрисовки модалки (возникал, если открывать модалку не по какому-либо событию, а изначально имея ключ isOpen={true}, не проставлялись css-классы в classNames у CSSTransition)
http://joxi.ru/8AnR5E3cy9ky4A.png

fix(Modal): added appear prop to CSSTransition

---

build.config.js

feat(createIcon): provided a function for export

---

src/hooks/useSelect/useSelect.tsx

fix(Selects): fixed scroll on hover in dropdown

---

src/components/Tooltip/Tooltip.tsx

fix(Tooltip): added className

---

.github/workflows/chromatic.yml
.gitignore

chore(chromatic): added config for gitHub actions

---

src/components/Attach/__tests__/Attach.test.tsx

test(Attach): added tests

---

src/components/Table/Cell/TableCell.css
src/components/Table/Cell/TableCell.tsx
src/components/Table/Header/TableHeader.css
src/components/Table/Header/TableHeader.tsx
src/components/Table/Resizer/TableResizer.tsx
src/components/Table/Table.css
src/components/Table/Table.tsx
src/components/Table/__mock__/data.mock.tsx
src/components/Table/__stories__/Table.stories.tsx
src/components/Table/__tests__/helpers.test.ts
src/components/Table/helpers.ts

Добавлена возможность использования многоуровневых заголовков в компоненте Table
https://github.com/gazprom-neft/consta-uikit/issues/396
https://github.com/gazprom-neft/consta-uikit/issues/425

feat(Table): added multilevel headers

---

src/components/Combobox/Combobox.tsx
src/components/Combobox/__stories__/Combobox.mdx
src/components/MultiCombobox/MultiCombobox.tsx
src/components/SelectComponents/SelectDropdown/SelectDropdown.css
src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
src/hooks/useSelect/useSelect.tsx

* added message if no items are found in the list
* if the value in the input is the same as the list item, then hide the item creation button
issue - #533 #532
Добавил сообщение при отсутствии элементов при поиске
Теперь кнопка "Добавить" не появляется если такой элемент уже есть в списке

feat(Combobox, MultiCombobox): added message if no items are found in the list

---

src/components/Switch/Switch.css
src/components/Switch/Switch.tsx
src/components/Switch/__stories__/Switch.mdx
src/components/Switch/__stories__/Switch.stories.tsx
src/components/Switch/__stories__/examples/SwitchExampleView/SwitchExampleView.tsx

closes #560
Добавлен новый модификатор view со значениями primary и ghost

feat(Switch): added view ghost

---

src/components/Radio/Radio.css
src/components/Radio/Radio.tsx
src/components/Radio/__stories__/Radio.mdx
src/components/Radio/__stories__/Radio.stories.tsx
src/components/Radio/__stories__/examples/RadioExampleView/RadioExampleView.tsx

closes #558 
Добавлен модификатор на внешний вид view со значениями primary и ghost

feat(Radio): added view ghost

---

src/components/Checkbox/Checkbox.css
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__stories__/Checkbox.mdx
src/components/Checkbox/__stories__/Checkbox.stories.tsx
src/components/Checkbox/__stories__/examples/CheckboxExampleView/CheckboxExampleView.tsx

closes #556
Добавлен модификатор view со значениями primary (по умолчанию) и ghost

feat(checkbox): added view ghost

---

src/components/Combobox/Combobox.tsx
src/components/Combobox/__mocks__/ResizeObserver.ts
src/components/MultiCombobox/__mocks__/ResizeObserver.ts
src/components/MultiCombobox/__tests__/MultiCombobox.test.tsx

test(MultiCombobox): added tests

---

src/components/SelectComponents/SelectDropdown/SelectDropdown.css

Дропдаун у селекта терялся при использовани в модалке, поднял z-index у него

fix(SelectDropdown): added z-index for dropdown list

---

src/components/Theme/_color/Theme_color_gpnDefault.css

Fix(theme) fix colors

---

src/components/Header/Header.css
src/components/Header/__stories__/Header.mdx
src/components/Header/__stories__/examples/HeaderButtonExample/HeaderButtonExample.css
src/components/Header/__stories__/examples/HeaderButtonExample/HeaderButtonExample.tsx
src/components/Header/__stories__/examples/HeaderFullExample/HeaderFullExample.tsx
src/components/Header/__stories__/examples/HeaderLoginExample/HeaderLoginExample.css
src/components/Header/__stories__/examples/HeaderLoginExample/HeaderLoginExample.tsx
src/components/Header/__stories__/examples/HeaderMenuExample/HeaderMenuExample.css
src/components/Header/__stories__/examples/HeaderMenuExample/HeaderMenuExample.tsx

docs(Header): add docs for Header

---

src/components/BasicSelect/BasicSelect.tsx
src/components/Combobox/Combobox.tsx
src/components/MultiCombobox/MultiCombobox.tsx
src/components/SelectComponents/Select.css
src/components/SelectComponents/SelectDropdown/SelectDropdown.css
src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
src/components/SelectComponents/helpers.ts

issue -  #531
Форма дропдауна теперь зависит от формы селекта

feat(Selects): added form modifier for dropdown

---

src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/ChoiceGroup/__stories__/ChoiceGroup.stories.tsx
src/components/Tabs/Tabs.tsx
src/hooks/useChoiceGroup/useChoiceGroup.tsx

исправил тип колбека, раньше при ` multiple = true` был `(props: { e: EVENT; value: ITEM | null }) => void;` но null по логике был недостижим, исправил на `(props: { e: EVENT; value: ITEM }) => void;`

fix(useChoiceGroup): fix type callBack function

---

.github/workflows/telegramBot.yml

chore(telegram): added telegram bot integration

---

.grenrc.js

chore(grenrc): edit template

---

src/components/Modal/Modal.css

Modal(fix): padding to space 

---

src/components/Radio/__stories__/Radio.stories.tsx
src/components/RadioGroup/RadioGroup.css
src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/__stories__/RadioGroup.mdx
src/components/RadioGroup/__stories__/RadioGroup.stories.tsx
src/components/RadioGroup/__tests__/RadioGroup.test.tsx
src/components/Theme/__stories__/examples/ThemeExampleColors/ThemeExampleColors.css

feat(RadioGroup): added RadioGroup component

---

src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/ChoiceGroup/Item/ChoiceGroup-Item.tsx
src/components/ChoiceGroup/__stories__/ChoiceGroup.mdx
src/components/ChoiceGroup/__tests__/ChoiceGroup.test.tsx
src/components/Theme/__stories__/examples/ThemeExampleColors/ThemeExampleColors.css

fixed types, fixed mixFocus
issue -  #617 #590

fix(ChoiceGroup): types, mixFocus

---

.github/CODEOWNERS

fix(CODEOWNERS): remove al-fyodorov

---

src/components/Modal/__stories__/Modal.stories.css
src/components/Modal/__stories__/examples/ModalExample/ModalExample.css
src/components/Pagination/Pagination.css
src/components/Pagination/Pagination.tsx
src/components/Pagination/__stories__/Pagination.mdx
src/components/Pagination/__stories__/Pagination.stories.css
src/components/Pagination/__stories__/Pagination.stories.tsx
src/components/Pagination/__tests__/Pagination.test.tsx
src/components/Pagination/__tests__/helpers.test.ts
src/components/Pagination/helpers.ts
src/components/Sidebar/__stories__/examples/SidebarExample/SidebarExample.css

feat(Pagination): added Pagination component

---

src/components/MultiCombobox/MultiCombobox.tsx
src/components/SelectComponents/Select.css

исправил ошибку неработающих крестиков на тегах

fix(MultiCombobox): fixed click on valueTag

---

src/components/Table/Cell/TableCell.tsx
src/components/Table/FilterTooltip/TableFilterTooltip.tsx
src/components/Table/Header/TableHeader.tsx
src/components/Table/Table.tsx
src/components/Table/__stories__/Table.mdx
src/components/Table/__stories__/Table.stories.tsx

[feat/table]: Добавить testid для ячеек и строк

---

src/uiKit/components/DocsDecorator/DocsDecorator.css

fix(Docs): update line-height for Headings

---

src/components/Header/Menu/HeaderMenu.css

closes #680 
Изменила цвета в меню шапки

bug(Header): изменение цветов ссылок в меню

---

src/components/Steps/Steps.css
src/components/Steps/Steps.tsx
src/components/Steps/StepsStep/StepsStep.css
src/components/Steps/StepsStep/StepsStep.tsx
src/components/Steps/__stories__/Steps.mdx
src/components/Steps/__stories__/Steps.stories.css
src/components/Steps/__stories__/Steps.stories.tsx
src/components/Steps/__tests__/Steps.test.tsx

Добавлен компонент Steps (https://github.com/gazprom-neft/consta-uikit/issues/661)

feat(Steps): new component

---

src/components/CheckboxGroup/CheckboxGroup.css
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/CheckboxGroup/__stories__/CheckboxGroup.mdx
src/components/CheckboxGroup/__stories__/CheckboxGroup.stories.tsx
src/components/CheckboxGroup/__tests__/CheckboxGroup.test.tsx

Добавлен компонент CheckboxGroup (https://github.com/gazprom-neft/consta-uikit/issues/165)

feat(CheckboxGroup): new component

---

src/components/Table/Table.tsx
src/components/Table/__stories__/Table.mdx
src/components/Table/filtering.ts

Добавил колбэк на изменение фильтров, чтобы можно было в моем проекте перезапросить с сервера уже отфильтрованные данные при применении фильтра (у нас там infinite scroll).

Filters updated callback

---

src/components/ContextMenu/ContextMenu.tsx
src/components/ContextMenu/ContextMenuDivider/ContextMenuDivider.css
src/components/ContextMenu/ContextMenuDivider/ContextMenuDivider.tsx
src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.css
src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.tsx
src/components/ContextMenu/ContextMenuItem/ContextMenuItem.css
src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.css
src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
src/components/ContextMenu/__mocks__/mock.data.ts
src/components/ContextMenu/__stories__/ContextMenu.mdx
src/components/ContextMenu/__stories__/ContextMenu.stories.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleGroups/ContextMenuExampleGroups.css
src/components/ContextMenu/__stories__/examples/ContextMenuExampleGroups/ContextMenuExampleGroups.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick.css
src/components/ContextMenu/__stories__/examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSide/ContextMenuExampleSide.css
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSide/ContextMenuExampleSide.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSimple/ContextMenuExampleSimple.css
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSimple/ContextMenuExampleSimple.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSubMenu/ContextMenuExampleSubMenu.css
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSubMenu/ContextMenuExampleSubMenu.tsx
src/components/ContextMenu/__tests__/ContextMenu.test.tsx
src/components/ContextMenu/__tests__/helpers.test.tsx
src/components/ContextMenu/helpers.tsx
src/components/Popover/Popover.tsx

issue - #595
Добавил компонент и документацию, документация требует доработки
тесты пока не написаны, будут позже

feat: (ContextMenu) added component

---

src/components/Table/Table.tsx

(https://github.com/gazprom-neft/consta-uikit/issues/566)

fix(Table): fix table grid columns (#566)

---

.eslintrc.js
builder/build.js
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/__stories__/Tooltip.mdx
src/components/Tooltip/__stories__/Tooltip.stories.tsx
src/hocs/withTooltip/__stories__/examples/WithTooltipExampleMode/WithTooltipExampleMode.tsx
src/hocs/withTooltip/__stories__/examples/WithTooltipExampleProps/WithTooltipExampleProps.tsx
src/hocs/withTooltip/__stories__/examples/WithTooltipExampleText/WithTooltipExampleText.tsx
src/hocs/withTooltip/__stories__/withTooltip.mdx
src/hocs/withTooltip/__stories__/withTooltip.stories.css
src/hocs/withTooltip/__stories__/withTooltip.stories.tsx
src/hocs/withTooltip/__tests__/withTooltip.test.tsx
src/hocs/withTooltip/withTooltip.tsx
src/hooks/useClickOutside/useClickOutside.tsx

issue -  #462 
Добавил хок, добавляющий на компонент тултип

feat(withTooltip): added HOC withTooltip

---

src/components/BasicSelect/BasicSelect.tsx
src/components/BasicSelect/__stories__/BasicSelect.stories.tsx
src/components/Combobox/Combobox.tsx
src/components/Combobox/__stories__/Combobox.stories.tsx
src/components/MultiCombobox/MultiCombobox.tsx
src/components/MultiCombobox/__stories__/MultiCombobox.stories.tsx
src/components/SelectComponents/types.ts

исправляет баг с прокруткой в списке  http://s.csssr.ru/UC5KAQ32R/2020-12-23-15-00-07-xrmj1.mp4

fix(focus): исправить blur

---

src/components/Button/Button.tsx
src/components/Button/__stories__/Button.stories.tsx
src/components/EventInterceptor/EventInterceptor.tsx
src/components/EventInterceptor/eventInterceptorMap.ts
src/components/EventInterceptor/propsHandlers/buttonEventHandler.tsx
src/components/EventInterceptor/usePropsHandler.tsx

Реализован контекст для подключения компонентов для использования СПА. Подключен компонент Button к этому контексту.

feat(EventInterceptor): added EventInterceptor context

---

src/components/Modal/Modal.tsx
src/components/Modal/__stories__/Modal.mdx

issue -  #741
добвил rootClassName

feat(Modal): added rootClassName prop

---

src/components/ProgressSpin/ProgressSpin.css
src/components/ProgressSpin/ProgressSpin.tsx

fix(ProgressSpin): fix SVG

---

src/components/BasicSelect/BasicSelect.tsx
src/components/Checkbox/Checkbox.tsx
src/components/EventInterceptor/EventInterceptor.tsx
src/components/EventInterceptor/propsHandlers/__tests__/useBasicSelectEventsHandler.test.tsx
src/components/EventInterceptor/propsHandlers/__tests__/useButtonEventHandler.test.tsx
src/components/EventInterceptor/propsHandlers/__tests__/useCheckboxEventsHandler.test.tsx
src/components/EventInterceptor/propsHandlers/__tests__/useSnackBarEventsHandler.test.tsx
src/components/EventInterceptor/propsHandlers/__tests__/useTextFieldEventsHandler.test.tsx
src/components/EventInterceptor/propsHandlers/useBasicSelectEventsHandler.tsx
src/components/EventInterceptor/propsHandlers/useButtonEventHandler.tsx
src/components/EventInterceptor/propsHandlers/useCheckboxEventsHandler.tsx
src/components/EventInterceptor/propsHandlers/useSnackBarEventsHandler.tsx
src/components/EventInterceptor/propsHandlers/useTextFieldEventsHandler.tsx
src/components/EventInterceptor/usePropsHandler.tsx
src/components/TextField/TextField.tsx

Обновил ссылки на компоненты в дом дереве. Обновил хэндлер эвента чекбокса.

fix(EventInterceptor): fixed event handlers

---

.github/CODEOWNERS

chore(CODEOWNERS): added @azhadanov

---

src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.css

issue -  #751, #752
Поправлено имя css переменной [#751](https://github.com/gazprom-neft/consta-uikit/issues/751) , добавлено свойство для заголовка группы [#752 ](https://github.com/gazprom-neft/consta-uikit/issues/752)

fix(contextMenu): fix css variable name and add letter spacing

---

src/components/Breadcrumbs/Breadcrumbs.css
src/components/Breadcrumbs/__stories__/Breadcrumbs.stories.tsx

Поправлен цвет активного элемента, отступы для всех размеров компонента.
Дополнительно исправлены адреса ссылок в стори на соответствующие лейблу.

fix(Breadcrumbs): fixed indents and font color

---

src/components/Modal/__stories__/Modal.stories.tsx

issue -  #692
Убрал стори "с combobox"

fix(Modal): remove story with combobox

---

src/components/Badge/Badge.css

issue -  #711
Высота теперь берется из переменных темы на контролы, а не задается в компоненте в пикселях.

fix(Badge): fixed height

---

src/components/Avatar/Avatar.css
src/components/Avatar/Avatar.tsx
src/components/Avatar/__stories__/Avatar.mdx
src/components/Avatar/__stories__/examples/AvatarExampleSize/AvatarExampleSize.tsx

issue -  #769
Добавлен xs-размер для компонента Avatar

feat(Avatar): add XS-size

---

src/components/SwitchGroup/SwitchGroup.css
src/components/SwitchGroup/SwitchGroup.tsx
src/components/SwitchGroup/__stories__/SwitchGroup.mdx
src/components/SwitchGroup/__stories__/SwitchGroup.stories.tsx
src/components/SwitchGroup/__tests__/SwitchGroup.test.tsx

issue -  #665
Создан компонент SwitchGroup по аналогии с RadioGroup и CheckboxGroup, по их же примерам написаны тесты, стори и документация

feat(SwitchGroup): add SwitchGroup component, story and tests

---

src/components/ChoiceGroup/ChoiceGroup.css

fix(ChoiceGroup): fixed input style on IOS

---

src/components/ContextMenu/__stories__/ContextMenu.mdx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSize/ContextMenuExampleSize.css
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSize/ContextMenuExampleSize.tsx

Поправила описание, добавила примеров (не везде, но их там и так много).
В конце нет примера использования, помогите, плиз, с ним, если считаете, что нужен.
- [ /] PR: направлен в правильную ветку
- [ /] PR: назначен исполнитель PR и указаны нужные лейблы

docs(ContextMenu): edit docs

---

src/components/Table/Cell/TableCell.tsx
src/components/Table/Header/TableHeader.css
src/components/Table/Header/TableHeader.tsx
src/components/Table/Table.tsx
src/components/Table/__stories__/Table.mdx
src/components/Table/__stories__/Table.stories.tsx

issue -  #808
Заголовок таблицы выровнен по нижнему краю. Был вертикально по центру

feat(table): table header's vertical align center → bottom

---

src/components/Tooltip/Tooltip.tsx

fix(Tooltip): fixed theme

---

src/components/Checkbox/Checkbox.css

issue -  #771
Исправлено центрирование и цвета для ghost при intermediate

fix(Checkbox): fixed centering and colors for intermediate

---

src/components/File/File.css

change color for Loader in File
issue -  #158
Захардкодил цвет лоадеру внутри файла

fix(components): file

---

.github/CODEOWNERS

chore(CODEOWNERS): update

---

package.json

chore(Prettier): add commit-formatting for mdx files

---

src/components/MultiCombobox/MultiCombobox.tsx

fix(MultiCombobox): fix clear value function

---

src/components/Tabs/Tab/TabsTab.css
src/components/Tabs/Tabs.css
src/components/Tabs/Tabs.tsx
src/hooks/useForkRef/useForkRef.tsx

* removed casting to types
* fixed css
* code optimizatio
issue -  #921

refactor(Tabs): removed casting to types and more fix

---

docs/common/about.mdx

docs(general): add remark about IE and old Edge version

---

src/components/Button/Button.tsx

feat(Button): added new sizes for modifier _onlyIcon

---

.github/CODEOWNERS

chore(CODEOWNERS): update CODEOWNERS

---

src/components/ThemeToggler/__stories__/ThemeToggler.stories.tsx

потерялась группировка, исправил

fix(storybook): add themeToggler to group in sidebar

---

README.md

Добавлено короткое описание, ссылки на тг-канал и сайт дизайн-системы.
Таск #1069

docs(readme): general info added

---

.storybook/main.js
docs/common/componentsPreview/ComponentsGrid/ComponentsGrid.css
docs/common/componentsPreview/ComponentsGrid/ComponentsGrid.tsx
docs/common/componentsPreview/preview.mdx

chore(Storybook): edit configs

---

src/components/Collapse/__stories__/Collapse.stories.tsx

fix grouping in storybook sidebar
issue -  #1099

fix(components): collapse

---

src/hooks/useThemeVars/useThemeVars.ts

feat(useThemeVars): export types

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-request.md

chore(github): Update issue templates

---

src/hooks/useThemeVars/helpers.ts
src/uiKit/components/ColorPreview/ColorPreview.css
src/uiKit/components/ColorPreview/ColorPreview.tsx
src/uiKit/components/ThemePreview/ThemePreview.css
src/uiKit/components/ThemePreview/ThemePreview.tsx
src/uiKit/components/ThemePreview/helpers.ts

docs(Theme): add color value preview and copy

---

src/hooks/useChoiceGroup/__stories__/useChoiceGroup.stories.mdx
src/hooks/useChoiceGroup/useChoiceGroup.tsx

feat(useChoiceGroup): publication useChoiceGroup

---

src/components/ThemeToggler/__tests__/ThemeToggler.test.tsx

issue - https://github.com/gazprom-neft/consta-uikit/issues/1044

feat(ThemeToggler): added tests

---

docs/common/developers/creatingPreset.stories.mdx
src/components/Modal/Modal.css
src/components/Theme/Theme.tsx
src/components/Theme/__stories__/Theme.docs.mdx
src/components/Theme/_shadow/Theme_shadow_gpnDefault.css
src/components/Theme/presets/presetGpnDark.ts
src/components/Theme/presets/presetGpnDefault.ts
src/components/Theme/presets/presetGpnDisplay.ts
src/hooks/useThemeVars/__stories__/useThemeVars.stories.mdx
src/hooks/useThemeVars/helpers.ts
src/hooks/useThemeVars/useThemeVars.ts
src/uiKit/components/ThemePreview/ThemePreview.tsx

issue - https://github.com/gazprom-neft/consta-uikit/issues/1055

feat(Theme): added shadow variables

---

src/components/Table/FilterContainer/TableFilterContainer.tsx
src/components/Table/NumberFilter/TableNumberFilter.tsx
src/components/Table/Table.tsx
src/components/Table/TextFilter/TableTextFilter.tsx
src/components/Table/__stories__/Table.docs.mdx

fix(Table): reexport filter components and TableFilterContainer

---

src/components/Tabs/Tab/TabsTab.css

fix(TabsTab): Поправил ЦСС, который валил билд CRA

---

src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.css
src/components/Informer/Informer.css
src/components/Popover/__stories__/Popover.stories.css
src/components/SelectComponents/SelectDropdown/SelectDropdown.css
src/components/Sidebar/Sidebar.css
src/components/SnackBar/Item/SnackBar-Item.css
src/components/Table/FilterContainer/TableFilterContainer.css
src/components/Table/FilterTooltip/TableFilterTooltip.css
src/components/Tooltip/Tooltip.css

issue - https://github.com/gazprom-neft/consta-uikit/issues/1205

feat(components): applied shadow variables

---

src/components/Theme/_color/Theme_color_gpnDefault.css

fix(Theme): fix color calculation parameter

---

src/hooks/useChoiceGroup/__stories__/useChoiceGroup.stories.mdx

docs(useChoiceGroup): edit docs

---

src/components/Collapse/__stories__/Collapse.docs.mdx
src/components/Collapse/__stories__/examples/CollapseExampleHover/CollapseExampleHover.tsx
src/components/Collapse/__stories__/examples/CollapseExampleIconCustomIcon/CollapseExampleIconCustomIcon.tsx
src/components/Collapse/__stories__/examples/CollapseExampleIconPosition/CollapseExampleIconPosition.tsx
src/components/Collapse/__stories__/examples/CollapseExampleIconRightSide/CollapseExampleIconRightSide.tsx
src/components/Collapse/__stories__/examples/CollapseExampleSpace/CollapseExampleSpace.tsx

issue -  #908
Добавила документацию и пару примеров, поправила примеры, ссылки, табличку и всё, что нашла.

docs(Collapse): add docs

---

src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/__mocks__/data.mock.ts
src/components/RadioGroup/__stories__/RadioGroup.docs.mdx
src/components/RadioGroup/__stories__/RadioGroup.stories.tsx
src/components/RadioGroup/__stories__/examples/RadioGroupExampleAlign/RadioGroupExampleAlign.tsx
src/components/RadioGroup/__stories__/examples/RadioGroupExampleDisabled/RadioGroupExampleDisabled.tsx
src/components/RadioGroup/__stories__/examples/RadioGroupExampleSize/RadioGroupExampleSize.tsx
src/components/RadioGroup/__stories__/examples/RadioGroupExampleUse/RadioGroupExampleUse.tsx
src/components/RadioGroup/__stories__/examples/RadioGroupExampleView/RadioGroupExampleView.tsx

issue -  817
Перетащила документацию из Radio, немного поменяла структуру, добавила ссылки и примеры.

docs(RadioGroup): edit docs, move docs from Radio

---

src/components/Radio/__stories__/Radio.docs.mdx
src/components/Radio/__stories__/Radio.stories.tsx
src/components/Radio/__stories__/examples/RadioExampleAlign/RadioExampleAlign.tsx
src/components/Radio/__stories__/examples/RadioExampleSize/RadioExampleSize.tsx
src/components/Radio/__stories__/examples/RadioExampleUse/RadioExampleUse.tsx

issue -  226
Перенесла часть документации про использование группы кнопок в RadioGroup, добавила примерчик, кое-что отредактирвовала.

docs(Radio): edit docs, move part to RadioGroup

---

src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/CheckboxGroup/__mocks__/data.mock.ts
src/components/CheckboxGroup/__stories__/CheckboxGroup.docs.mdx
src/components/CheckboxGroup/__stories__/examples/CheckboxGroupExampleDirection/CheckboxGroupExampleDirection.tsx
src/components/CheckboxGroup/__stories__/examples/CheckboxGroupExampleDisabled/CheckboxGroupExampleDisabled.tsx
src/components/CheckboxGroup/__stories__/examples/CheckboxGroupExampleName/CheckboxGroupExampleName.tsx
src/components/CheckboxGroup/__stories__/examples/CheckboxGroupExampleSize/CheckboxGroupExampleSize.tsx
src/components/CheckboxGroup/__stories__/examples/CheckboxGroupExampleView/CheckboxGroupExampleView.tsx

issue -  816
Отредактировала документацию, перенесла часть примеров из Checkbox.

docs(CheckboxGroup): edit docs

---

.eslintrc.js
package.json
src/components/DragNDropField/DragNDropField.css
src/components/DragNDropField/DragNDropField.tsx
src/components/DragNDropField/DragNDropFieldContent/DragNDropFieldContent.css
src/components/DragNDropField/DragNDropFieldContent/DragNDropFieldContent.tsx
src/components/DragNDropField/DragNDropFieldContent/__tests__/helpers.ts
src/components/DragNDropField/DragNDropFieldContent/helpers.ts
src/components/DragNDropField/DragNDropFieldTooltip/DragNDropFieldTooltip.css
src/components/DragNDropField/DragNDropFieldTooltip/DragNDropFieldTooltip.tsx
src/components/DragNDropField/__stories__/DragNDropField.docs.mdx
src/components/DragNDropField/__stories__/DragNDropField.stories.tsx
src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleAccept/DragNDropFieldExampleAccept.tsx
src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleChildren/DragNDropFieldExampleChildren.tsx
src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleMaxSize/DragNDropFieldExampleMaxSize.tsx
src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleMultiple/DragNDropFieldExampleMultiple.tsx
src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleOnDropFiles/DragNDropFieldExampleOnDropFiles.tsx
src/components/DragNDropField/__tests__/helpers.test.ts
src/components/DragNDropField/helpers.ts
yarn.lock

feat(DragNDropField): added new component and examples

---

src/components/Combobox/Combobox.tsx
src/components/Combobox/helpers.ts
src/components/Select/Select.tsx
src/components/Select/helpers.ts
src/components/UserSelect/UserSelect.tsx
src/components/UserSelect/helpers.ts

issue -  #387
Думаю при сложностях прокинуть ref к компонентам где используются дженерики использовать такой подход. Тем самым с точки зрения кода все работает адекватно. С точки зрения типов, типы коммпонета работают типы внутри компонента тоже.

feat(Select): added ref

---

src/components/Popover/Popover.tsx

fix(Table): fixed filter portals

---

src/components/UserSelect/UserSelectItem/UserSelectItem.css
src/components/UserSelect/UserSelectItem/UserSelectItem.tsx

fix(UserSelect): fixed disable state of item

---

src/components/UserSelect/__stories__/UserSelect.docs.mdx
src/components/UserSelect/__stories__/examples/UserSelectExampleCreate/UserSelectExampleCreate.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleCustomTypes/UserSelectExampleCustomTypes.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleDisabled/UserSelectExampleDisabled.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleDisabledItem/UserSelectExampleDisabledItem.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleForm/UserSelectExampleForm.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleGroups/UserSelectExampleGroups.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleItems/UserSelectExampleItems.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleMultiple/UserSelectExampleMultiple.tsx
src/components/UserSelect/__stories__/examples/UserSelectExamplePlaceholder/UserSelectExamplePlaceholder.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleRenderItem/UserSelectExampleRenderItem.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleRenderValue/UserSelectExampleRenderValue.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleSize/UserSelectExampleSize.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleView/UserSelectExampleView.tsx

issue -  1326
Отредактировала документацию.

docs(UserSelect): edit docs and examples

---

src/components/Avatar/Avatar.css
src/components/Badge/Badge.css
src/components/Button/Button.css
src/components/ChoiceGroup/ChoiceGroup.css
src/components/Responses/Responses.css
src/components/SelectComponents/Select.css
src/components/SelectComponentsDeprecated/Select.css
src/components/Steps/StepsStep/StepsStep.css
src/components/Table/Cell/TableCell.css
src/components/Text/Text.css
src/components/TextField/TextField.css
src/components/Theme/_size/Theme_size_gpnDefault.css
src/components/Timer/Timer.css

feat(Theme): add font-weight variables

---

src/components/CollapseGroup/useChoice.ts

Иправил поведение аккордиона, стало возможным скрыть все элементы.

fix(CollapseGroup): fixed accordion behavior

---

src/components/Combobox/__stories__/Combobox.docs.mdx
src/components/Combobox/__stories__/examples/ComboboxExampleCreate/ComboboxExampleCreate.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleCustomTypes/ComboboxExampleCustomTypes.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleDisabled/ComboboxExampleDisabled.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleDisabledItem/ComboboxExampleDisabledItem.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleForm/ComboboxExampleForm.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleGroups/ComboboxExampleGroups.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleItems/ComboboxExampleItems.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleMultiple/ComboboxExampleMultiple.tsx
src/components/Combobox/__stories__/examples/ComboboxExamplePlaceholder/ComboboxExamplePlaceholder.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleRenderItem/ComboboxExampleRenderItem.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleRenderValue/ComboboxExampleRenderValue.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleSize/ComboboxExampleSize.tsx
src/components/Combobox/__stories__/examples/ComboboxExampleView/ComboboxExampleView.tsx

Отредактировала доку и примеры

docs(combobox): edit docs & example

---

src/components/CollapseGroup/__mocks__/mock.data.tsx
src/components/CollapseGroup/__stories__/CollapseGroup.docs.mdx
src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleOwnType/CollapseGroupExampleOwnType.tsx
src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleSimple/CollapseGroupExampleSimple.tsx

issue -  909
Отредактировала документацию, добавила примеры и ссылки на коллапс.

docs(CollapseGroup): edit docs & examples

---

src/components/DragNDropField/DragNDropField.css
src/components/DragNDropField/DragNDropField.tsx

fix(DragNDropField): show custom view while dragging files

---

README.md

Переписала ридми: добавила ссылки на лендинг, графики, фигму и пр.

docs(readme): edit readme

---

src/components/Calendar/CalendarCell/CalendarCell.css
src/components/Calendar/CalendarGrid/CalendarGrid.css
src/components/Calendar/CalendarGrid/CalendarGrid.tsx
src/components/Calendar/CalendarMonth/CalendarMonth.css
src/components/Calendar/CalendarMonth/CalendarMonth.tsx

feat(Calendar): add CalendarGrid

---

src/components/Calendar/Calendar.tsx
src/components/Calendar/CalendarCell/CalendarCell.css
src/components/Calendar/CalendarCell/CalendarCell.tsx
src/components/Calendar/CalendarGrid/CalendarGrid.css
src/components/Calendar/CalendarGrid/CalendarGrid.tsx
src/components/Calendar/CalendarMonth/CalendarMonth.css
src/components/Calendar/CalendarMonth/CalendarMonth.tsx
src/components/Calendar/helpers.ts

fix(Calendar): fix name CalendarCell

---

src/components/Calendar/Calendar.css
src/components/Calendar/Calendar.tsx
src/components/Calendar/Calendar10Years/Calendar10Years.css
src/components/Calendar/Calendar10Years/Calendar10Years.tsx
src/components/Calendar/CalendarCell/CalendarCell.css
src/components/Calendar/CalendarGrid/CalendarGrid.css
src/components/Calendar/CalendarItem/CalendarItem.css
src/components/Calendar/CalendarYear/CalendarYear.css
src/components/Calendar/CalendarYear/CalendarYear.tsx
src/components/Calendar/__stories__/Calendar.stories.tsx

Добавил компоненты CalendarYear и Calendar10Years

feat(Calendar): add CalendarYear and Calendar10Years

---

src/components/Table/__stories__/Table.stories.tsx
src/components/Table/filtering.ts

issue - #1189
Добавил вызов колбэка onFiltersUpdated в функцию removeAllSelectedFilters

fix(Table): fixed onFiltersUpdated not called on removeAllSelectedFilters

---

src/components/Table/FilterContainer/TableFilterContainer.css
src/components/Table/FilterContainer/TableFilterContainer.tsx

feat(TableNumberFilter): added className props

---

src/components/Table/Table.css

fix(Table): removed vertical scroll when table is empty

---

src/components/Text/Text.css
src/components/Text/Text.tsx
src/components/Text/__stories__/Text.docs.mdx
src/components/Text/__stories__/Text.stories.tsx

Closes #1081
Добавлены пропсы отвечающие за курсор и подчеркивание. Они работают отдельно от view

feat(Text): Add underline & cursor props

---

src/components/User/__stories__/User.stories.tsx

fix(User): исправить опечатку

---

src/components/SwitchGroup/__stories__/SwitchGroup.docs.mdx
src/components/SwitchGroup/__stories__/SwitchGroup.stories.tsx
src/components/SwitchGroup/__stories__/examples/SwitchGroupExampleDirection/SwitchGroupExampleDirection.tsx
src/components/SwitchGroup/__stories__/examples/SwitchGroupExampleDisabled/SwitchGroupExampleDisabled.tsx
src/components/SwitchGroup/__stories__/examples/SwitchGroupExampleSize/SwitchGroupExampleSize.tsx
src/components/SwitchGroup/__stories__/examples/SwitchGroupExampleView/SwitchGroupExampleView.tsx

issue -  #947
Переписала доку, добавила визуальные примеры (не было ни одного).

docs(SwitchGroup): edit docs, add examples

---

src/components/Select/__mocks__/data.mock.ts
src/components/Select/__stories__/Select.docs.mdx
src/components/Select/__stories__/Select.stories.tsx

issue -  #947
Поменяла пример в стори, поправила порядок примеров в доке (заодно появились отступы).

docs(Select): docs review

---

src/components/ChoiceGroup/__stories__/ChoiceGroup.docs.mdx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleText/ChoiceGroupExampleText.tsx

issue -  #947
Добавила примеры кода, немножко переделала структуру,  текст кое-где поправила.

docs(ChoiceGroup): docs review

---

src/components/Checkbox/__stories__/Checkbox.docs.mdx

issue -  #947
Поправила опечатку, поменяла местами примеры кода и превью.

docs(Checkbox): docs review

---

src/components/Button/__stories__/Button.docs.mdx
src/components/Button/__stories__/Button.stories.tsx

Поменяла текст на кнопке в стори, поменяла местами примеры и код, что-то ещё по мелочи.

docs(Button): docs review

---

src/components/BasicSelectDeprecated/__stories__/BasicSelect.docs.mdx
src/components/BasicSelectDeprecated/__stories__/BasicSelect.stories.tsx
src/components/BasicSelectDeprecated/__stories__/examples/BasicSelectExampleText/BasicSelectExampleText.tsx

Поправила примеры в стори и в доке в рамках ревью.

docs(BasicSelect): docs review

---

src/components/Tabs/FitModeScrollWrapper/TabsFitModeScrollWrapper.css

Change overflow property from hidden to scroll and also hide the horizontal scrollbar
issue -  #1441
* Добавлена возможность прокручивания жестами
* Убран горизонтальный скролбар

feat(TabsFitModeScrollWrapper): add native scroll

---

src/components/DateTime/DateTime.tsx
src/components/DateTime/DateTimeLabel/DateTimeLabel.tsx
src/components/DateTime/DateTimeSlider/DateTimeSlider.css
src/components/DateTime/DateTimeToggler/DateTimeToggler.tsx
src/components/DateTime/DateTimeTypeYearViewBook/DateTimeTypeYearViewBook.css
src/components/DateTime/DateTimeTypeYearViewSlider/DateTimeTypeYearViewSlider.css
src/components/DateTime/DateTimeTypeYearViewSlider/DateTimeTypeYearViewSlider.tsx
src/components/DateTime/__stories__/DateTime.stories.tsx

feat(DateTime): add DateTimeTypeYearViewSlider

---

src/components/DateTime/DateTime.tsx
src/components/DateTime/DateTimeLabel/DateTimeLabel.tsx
src/components/DateTime/DateTimeSlider/DateTimeSlider.css
src/components/DateTime/DateTimeToggler/DateTimeToggler.tsx
src/components/DateTime/DateTimeTypeYearViewBook/DateTimeTypeYearViewBook.css
src/components/DateTime/DateTimeTypeYearViewBook/DateTimeTypeYearViewBook.tsx
src/components/DateTime/DateTimeTypeYearViewSlider/DateTimeTypeYearViewSlider.css
src/components/DateTime/DateTimeTypeYearViewSlider/DateTimeTypeYearViewSlider.tsx
src/components/DateTime/__stories__/DateTime.stories.tsx

feat(DateTime): add DateTimeTypeYearViewBook

---

src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
src/hocs/withTooltip/withTooltip.tsx

Closes #1297
Поправил тайпинги и пару опечаток

feat(withTooltip,ContextMenuLevel): Fixed typings & typos

---

src/components/DateTime/DateTime.tsx
src/components/DateTime/DateTimeTime/DateTimeTime.css
src/components/DateTime/DateTimeTime/DateTimeTime.tsx
src/components/DateTime/DateTimeTime/helpers.ts
src/components/DateTime/DateTimeTimeColumn/DateTimeTimeColumn.tsx
src/components/DateTime/DateTimeTypeTime/DateTimeTypeTime.css
src/components/DateTime/DateTimeTypeTime/DateTimeTypeTime.tsx
src/components/DateTime/__stories__/DateTime.stories.tsx
src/components/DateTime/helpers/index.ts
src/components/DateTime/helpers/types.ts
src/hooks/useMutableRef/useMutableRef.ts

feat(DateTime): add DateTimeTypeTime

---

src/components/Table/__tests__/Table.test.tsx

test(Table): added test for onRowClick

---

src/components/Table/__tests__/Table.test.tsx

test(Table): added test for checking onFiltersUpdated call

---

src/components/Text/Text.css
src/components/Text/Text.tsx
src/components/Text/__stories__/Text.docs.mdx
src/components/Text/__stories__/Text.stories.tsx
src/components/Text/__stories__/examples/TextExampleEllipsis/TextExampleEllipsis.tsx
src/components/Text/__stories__/examples/TextExampleTruncate/TextExampleTruncate.tsx

feat(Text): added prop ellipsis and update docs

---

src/components/Card/__stories__/Card.docs.mdx
src/components/Card/__stories__/examples/CardExampleForm/CardExampleForm.tsx
src/components/Card/__stories__/examples/CardExampleShadow/CardExampleShadow.tsx
src/components/Card/__stories__/examples/CardExampleSpace/CardExampleSpace.tsx
src/components/Card/__stories__/examples/CardExampleState/CardExampleState.tsx

closes #1129
Дописала доку, добавила примеров.

docs(Card): edit docs

---

src/components/Switch/Switch.css

fix(Switch): updated background-color disabled state

---

src/components/Table/__tests__/Table.test.tsx

Closes #987
Добавлены тесты для случая mergeCells

test(Table): Add test case for mergeCells

---

src/components/Collapse/Collapse.css
src/components/Collapse/Collapse.tsx

closes #1431
* Вынесен разделитель из лэйбла в тело коллапса

feat(Collapse): add divider from label to body

---

src/components/ProgressStepBarCanary/__stories__/ProgressStepBar.docs.mdx
src/components/ProgressStepBarCanary/__stories__/examples/ProgressStepBarExampleActive/ProgressStepBarExampleActive.tsx
src/components/ProgressStepBarCanary/__stories__/examples/ProgressStepBarExampleContent/ProgressStepBarExampleContent.tsx
src/components/ProgressStepBarCanary/__stories__/examples/ProgressStepBarExampleDirection/ProgressStepBarExampleDirection.tsx
src/components/ProgressStepBarCanary/__stories__/examples/ProgressStepBarExampleSize/ProgressStepBarExampleSize.tsx
src/components/ProgressStepBarCanary/__stories__/examples/ProgressStepBarExampleTooltip/ProgressStepBarExampleTooltip.tsx

closes #1667
Просто привела в порядок доку: добавила примеры кода и визуальные примеры, где не хватало, поправила навигацию.

docs(ProgressStepBar): edit docs, add examples

---

src/components/ContextMenu/helpers.tsx

fix(ContextMenu): edit getOnClick type

---

src/hooks/useSelect/useSelect.ts

closes #1717
* Исправлен баг, когда при имеющихся вариантах выбора отображалось сообщение, что ничего не найдено

fix(Combobox): fix bug with notFoundLabel

---

src/components/Table/Table.tsx

add minColumnWidth prop

---

src/components/Avatar/Avatar.css
src/components/Avatar/Avatar.tsx

feat(Avatar): add L size

---

src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
src/components/TextField/TextField.tsx
src/components/TextField/helpers.ts

docs(DatePicker): edit knobs

---

src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx

closes #906
Проверила доку (с ней всё ок), добавила в начало примечание о том, что описаны не все свойства. (Раз у меня возник такой вопрос, скорее всего, ещё у кого-то он возникнет.)

docs(DatePicker): add note about this doc

---

src/components/TextField/__stories__/TextField.docs.mdx

docs(TextField): fix examples code

---

src/components/SnackBar/SnackBar.css
src/components/SnackBar/__stories__/SnackBar.stories.css

closes #1746
* Добавлена адаптивность для компонента SnackBar

feat(SnackBar): add adaptivity for SnackBar

---

src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Button/Button.tsx
src/components/Calendar/Calendar.tsx
src/components/Calendar/__stories__/Calendar.stories.tsx
src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/Collapse/Collapse.tsx
src/components/Collapse/__stories__/Collapse.stories.tsx
src/components/CollapseGroup/__tests__/CollapseGroup.test.tsx
src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.tsx
src/components/DatePickerCanary/DatePickerFieldTypeDateRange/DatePickerFieldTypeDateRange.tsx
src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
src/components/DateTimeCanary/DateTimeCanary.tsx
src/components/DateTimeCanary/__stories__/DateTime.stories.tsx
src/components/ProgressSpin/ProgressSpin.tsx
src/components/ProgressStepBarCanary/ProgressStepBarLine/ProgressStepBarLine.tsx
src/components/SelectComponents/SelectItem/SelectItem.tsx
src/components/SelectComponentsDeprecated/SelectItem/SelectItem.tsx
src/components/Steps/StepsStep/StepsStep.tsx
src/components/Tabs/Tab/TabsTab.tsx
src/components/TagBase/TagBase.tsx
src/components/TextField/TextField.tsx
src/components/ThemeToggler/ThemeToggler.tsx
src/components/User/User.tsx
src/utils/getByMap.test.tsx
src/utils/getByMap.tsx

closes #1148
* Переименован метод getSizeByMap в getMyBap

refactor(getSizeByMap): rename from getSizeByMap to  getByMap

---

src/components/Theme/_color/Theme_color_gpnDark.css
src/components/Theme/_color/Theme_color_gpnDefault.css
src/components/Theme/_color/Theme_color_gpnDisplay.css

closes #882
* Изменены системный цвета для текста и фона: --color-bg-system, --color-typo-system

fix(Theme): fix system colors

---

src/components/Button/Button.tsx

Добавил внутренний ref в Button для решения https://github.com/gazprom-neft/consta-uikit/issues/1770

fix(Button): add inner ref

---

src/mixs/MixSpace/__stories__/MixSpace.stories.mdx
src/mixs/MixSpace/__stories__/examples/MixSpaceExample/MixSpaceExample.tsx

closes #1795
Добавила в доку пару примеров, поправила мелочи

docs(MixSpace): edit docs, add examples

---

package.json

chore(deps): change peerDependencies

---

src/components/Button/Button.tsx
src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleDisabled/ChoiceGroupExampleDisabled.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleForm/ChoiceGroupExampleForm.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleIcon/ChoiceGroupExampleIcon.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleMultiple/ChoiceGroupExampleMultiple.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleSize/ChoiceGroupExampleSize.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleSomeDisabled/ChoiseGroupExampleSomeDisabled.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleSwitch/ChoiceGroupExampleSwitch.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleText/ChoiceGroupExampleText.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleTextOverflow/ChoiceGroupExampleTextOverflow.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleView/ChoiceGroupExampleView.tsx
src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleWidth/ChoiceGroupExampleWidth.tsx
src/components/Table/ChoiceGroupFilter/TableChoiceGroupFilter.tsx

fix(ChoiceGroup): fixed multiple type

---

src/components/EventInterceptor/eventInterceptorMap.ts
src/components/EventInterceptor/propsHandlers/useButtonEventHandler.tsx
src/components/EventInterceptor/propsHandlers/useCheckboxEventsHandler.tsx
src/components/EventInterceptor/propsHandlers/useSelectEventsHandler.tsx
src/components/EventInterceptor/propsHandlers/useSnackBarEventsHandler.tsx
src/components/EventInterceptor/propsHandlers/useTextFieldEventsHandler.tsx

fix(EventInterceptor): fixed import loop in eventInterceptorMap

---

src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.css
src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.tsx
src/components/ProgressStepBarCanary/__stories__/ProgressStepBar.stories.tsx
src/components/ProgressStepBarCanary/helpers.ts

closes #1697
* Свойство `label` сделано опциональным
* Изменен пример в песочнице

feat(ProgressStepBar): change example on playground and also change label prop to optional

---

src/components/Attachment/__stories__/Attachment.docs.mdx

closes #947
В рамках ревью доки:
- добавила описание `withAction`,
- поменяла местами примеры и код,
- добавила импорт,
- добавила код примеров кое-куда.

docs(Attachment): docs review

---

src/components/UserSelect/__stories__/UserSelect.docs.mdx
src/components/UserSelect/__stories__/UserSelect.stories.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleCaption/UserSelectExampleCaption.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleCreate/UserSelectExampleCreate.tsx
src/components/UserSelect/__stories__/examples/UserSelectExampleLabel/UserSelectExampleLabel.tsx

closes #947
В рамках ревью документации:
- добавила описание и примеры для labelForCreate и labelForNotFound,
- отредактировала описание и добавила примеров для лейбла и подписи,
- поменяла местами примеры и и код,
- поправила опечаточки,
- добавила импорт.

docs(UserSelect): docs review

---

src/components/ContextMenu/ContextMenuItem/ContextMenuItem.css
src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
src/components/ContextMenu/helpers.tsx

feat(ContextMenu): added getItemAs and getItemHTMLAttributes

---

src/mixs/MixSpace/MixSpace.css
src/mixs/MixSpace/MixSpace.tsx
src/mixs/MixSpace/__stories__/MixSpace.stories.mdx

closes #1843 
Добавлены два новых значения для отступов: `0` | `auto`

feat(MixSpace): add new values for padding & margin

---

src/components/Collapse/__mocks__/mock.data.ts
src/components/Collapse/__stories__/Collapse.docs.mdx
src/components/Collapse/__stories__/Collapse.stories.tsx

closes #947
Поправила в рамках ревью доки: убрала  lorem ipsum, добавила код примеров, добавила импорт, поменяла примеры и код местами.

docs(Collapse): docs review

---

src/components/Table/NumberFilter/TableNumberFilter.tsx
src/components/TextField/TextField.tsx

fix bug with non-working autofocus in some containers
closes #1719
Исправлен баг, при котором нативный автофокус не работает в различных компонентах контейнерах

fix(TextField): fix bug with non-working autofocus

---

src/hooks/useBreakpoints/__stories__/useBreakpoints.stories.mdx
src/hooks/useBreakpoints/useBreakpoints.ts

feat(useBreakpoints): add hook useBreakpoints

---

src/components/Checkbox/Checkbox.css

refactor(Checkbox): edit code

---

src/components/SnackBar/Item/SnackBar-Item.tsx
src/components/SnackBar/SnackBar.tsx

closes #1839
Исправлена ошибка связанная с CSSTransaction & StrictMode

fix(SnackBar): fix warning with findDOMNode

---

src/components/Theme/_size/Theme_size_gpnDefault.css

fix(Theme): fixed --line-height-text-2xs

---

src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleCaption/DatePickerExampleCaption.tsx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleLabel/DatePickerExampleLabel.tsx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleRequired/DatePickerExampleRequired.tsx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleStatus/DatePickerExampleStatus.tsx
src/components/DatePickerCanary/helpers.ts

closes #1653
Внесенные изменения:
* Добавлены свойства: label, caption, labelPosition, required
* Обновлена документация для новых свойств
* Обновлены кнобы в песочнице

feat(DatePicker): add label and caption props, update docs and playground

---

src/mixs/MixCard/MixCard.css

closes #1887
Исправлен баг с отступами

fix(MixCard): fix  mistakes in stylesheet file

---

src/components/Timer/__stories__/Timer.docs.mdx

closes #947
Поправила мелочи в рамках ревью доки.

docs(Timer): docs reivew

---

src/components/SnackBar/__stories__/SnackBar.docs.mdx

closes #947
Добавила код примеров.

docs(SnackBar): docs review

---

src/components/Badge/__stories__/Badge.docs.mdx
src/components/Badge/__stories__/Badge.stories.tsx

closes #947
Поправила мелочи в рамках ревью доки: вопросики в табличке проставила, убрала английский, поправила примеры.

docs(Badge): docs review

---

src/components/ThemeToggler/__stories__/ThemeToggler.docs.mdx

closes #947
Поправила мелочи в рамках ревью.

docs(ThemeToggler): docs review

---

src/components/Sidebar/__stories__/Sidebar.docs.mdx
src/components/Sidebar/__stories__/Sidebar.stories.tsx
src/components/Sidebar/__stories__/examples/SidebarExample/SidebarExample.tsx

closes #947
Убрала lorem ipsum из примеров в рамках ревью.

docs(Sidebar): docs review

---

src/components/BreadcrumbsCanary/Breadcrumbs.css
src/components/BreadcrumbsCanary/BreadcrumbsCanary.tsx
src/components/BreadcrumbsCanary/__stories__/Breadcrumbs.docs.mdx
src/components/BreadcrumbsCanary/__stories__/Breadcrumbs.image.svg
src/components/BreadcrumbsCanary/__stories__/Breadcrumbs.stories.tsx
src/components/BreadcrumbsCanary/__stories__/examples/BreadcrumbsExample/BreadcrumbsExample.tsx
src/components/BreadcrumbsCanary/__tests__/Breadcrumbs.test.tsx
src/components/BreadcrumbsCanary/helpers.ts
src/components/BreadcrumbsCanary/types.ts

feat(BreadcrumbsCanary): add component

---

src/components/Table/__stories__/Table.stories.tsx

closes #1762  
Исправлен баг с возникновением критической ошибки при изменении данных во вкладке "рендер ячеек"

fix(Table): fix bug with render function

---

src/components/SliderCanary/SliderCanary.tsx

fix(Slider): removed warnings about required keys

---

src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleMulti/DatePickerExampleMulti.tsx

Отредактировала документацию, добавила пример.

docs(DatePicker): edit docs

---

src/hooks/useRefs/useRefs.ts

closes #2002
добавил хук для создания сразу нескольких ссылок

feat(useRefs): add hook useRefs

---

.eslintrc.js
src/hooks/useHideElementsInLine/useHideElementsInLine.ts
src/hooks/useRefs/useRefs.ts

closes #2003
хук для скрытия элементов в одной линии

feat(useHideElementsInLine): add hook

---

.eslintrc.js
src/hooks/useHideElementsInLine/useHideElementsInLine.ts
src/hooks/useRefs/useRefs.ts
src/mixs/MixDropdownAnimate/MixDropdownAnimate.css
src/mixs/MixDropdownAnimate/MixDropdownAnimate.tsx

миксин анимации раскрытия и скрытия дропдаунов

feat(MixDropdownAnimate): add mix 

---

.eslintrc.js
src/components/ContextMenu/ContextMenu.tsx
src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.css
src/components/ContextMenu/helpers.tsx
src/hooks/useHideElementsInLine/useHideElementsInLine.ts
src/hooks/useRefs/useRefs.ts
src/mixs/MixDropdownAnimate/MixDropdownAnimate.css
src/mixs/MixDropdownAnimate/MixDropdownAnimate.tsx

feat(ContextMenu): add ref for component

---

src/components/ContextMenu/ContextMenuItem/ContextMenuItem.css

fix(ContextMenuItem): fix cascading styles

---

src/components/Skeleton/__stories__/Skeleton.stories.tsx

fix(Storybook): fixed link to Skeleton

---

src/components/DateTimeCanary/DateTimeTimeColumn/useScrollToElement/useScrollToElement.ts
src/components/DateTimeCanary/DateTimeTypeTime/DateTimeTypeTime.tsx
src/components/DateTimeCanary/helpers/getSliderValueRange.ts

refactor(DateTime): small code change

---

src/components/BreadcrumbsCanary/__stories__/Breadcrumbs.docs.mdx
src/components/BreadcrumbsCanary/__stories__/examples/BreadcrumbsExample/BreadcrumbsExample.tsx

docs(Breadcrumbs): edit docs

---

docs/common/developers/createIcons.stories.mdx
src/icons/Icon/__stories__/Icon.docs.mdx

closes #866
Вытащила со странички с иконками раздел про создание своих иконок и перенесла в раздел Разработчикам.

docs(Icons): add create icons page

---

src/components/Responses/__stories__/Responses.docs.mdx
src/components/Responses/__stories__/examples/ResponsesExample/ResponsesExample.tsx

closes #2019
Добавила в документацию пример с ResponsesExit

docs(Responces): add ResponsesExit to the docs

---

src/components/DatePickerCanary/DatePickerDropdown/DatePickerDropdown.css
src/components/DatePickerCanary/DatePickerDropdown/DatePickerDropdown.tsx
src/components/DatePickerCanary/DatePickerTypeDate/DatePickerTypeDate.tsx
src/components/DatePickerCanary/DatePickerTypeDateRange/DatePickerTypeDateRange.tsx
src/components/DatePickerCanary/DatePickerTypeDateTime/DatePickerTypeDateTime.tsx
src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
src/components/DatePickerCanary/__tests__/DatePicker.test.tsx
src/components/DatePickerCanary/__tests__/DatePicker_type_date.test.tsx
src/components/DatePickerCanary/__tests__/DatePicker_type_dateRange.test.tsx
src/components/DatePickerCanary/__tests__/DatePicker_type_dateTime.test.tsx
src/components/DatePickerCanary/__tests__/helpers.ts
src/components/DateTimeCanary/__tests__/DateTime.test.tsx
src/components/DateTimeCanary/__tests__/DateTimeToggler.test.tsx
src/components/DateTimeCanary/__tests__/DateTime_type_date.test.tsx
src/components/DateTimeCanary/__tests__/DateTime_type_dateTime.test.tsx
src/components/DateTimeCanary/__tests__/DateTime_type_month.test.tsx
src/components/DateTimeCanary/__tests__/DateTime_type_time.test.tsx
src/components/DateTimeCanary/__tests__/DateTime_type_year.test.tsx
src/components/DateTimeCanary/__tests__/helpers.ts

test(DatePicker): add tests

---

src/hooks/useTimer/useTimer.tsx

closes #1891
Исправлен баг с утечкой памяти

fix(useTimer): fix bug with memory leak

---

src/hooks/useSelect/useSelect.ts

closes #2018 
Исправлен баг с появлением ошибки Uncaught TypeError

fix(useSelect): fix bug with Uncaught TypeError

---

src/components/DatePickerCanary/DatePickerCanary.tsx
src/components/DatePickerCanary/DatePickerDropdown/DatePickerDropdown.tsx
src/components/DatePickerCanary/DatePickerFieldTypeDateTimeRange/DatePickerFieldTypeDateTimeRange.tsx
src/components/DatePickerCanary/DatePickerFieldTypeDateTimeRange/helpers.ts
src/components/DatePickerCanary/DatePickerMixRangeField/DatePickerMixRangeField.css
src/components/DatePickerCanary/DatePickerMixRangeField/DatePickerMixRangeField.ts
src/components/DatePickerCanary/DatePickerTypeDateTimeRange/DatePickerTypeDateTimeRange.tsx
src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleType/DatePickerExampleType.tsx
src/components/DatePickerCanary/__tests__/DatePicker_type_dateRange.test.tsx
src/components/DatePickerCanary/__tests__/DatePicker_type_dateTime.test.tsx
src/components/DatePickerCanary/__tests__/DatePicker_type_dateTimeRange.test.tsx
src/components/DatePickerCanary/helpers.ts
src/components/DateTimeCanary/DateTimeTypeDateTime/DateTimeTypeDateTime.tsx
src/components/DateTimeCanary/DateTimeTypeDateTime/useOnChange.ts
src/components/DateTimeCanary/__tests__/DateTime_type_date.test.tsx
src/components/DateTimeCanary/__tests__/DateTime_type_month.test.tsx
src/components/DateTimeCanary/__tests__/DateTime_type_year.test.tsx
src/components/DateTimeCanary/helpers/types.ts

feat(DatePicker): add date-time-range type

---

src/components/Collapse/CollapseIcon/CollapseIcon.tsx
src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
src/components/SelectComponentsDeprecated/SelectDropdown/SelectDropdown.tsx
src/components/Sidebar/Sidebar.tsx
src/components/UserSelect/UserSelectItem/UserSelectItem.tsx
src/components/UserSelectDeprecated/UserSelectItem/UserSelectItem.tsx

closes #2034
Исправлен варнинг с Transaction

fix(CssTransition): fix warning with finDOMNode in Transaction children

---

src/components/Table/__stories__/Table.stories.tsx

closes #2049
Исправила ссылку на таблицу с обзора, заодно проверила все остальные ссылки, они работают.

docs(review): fix link to the Table

---

src/components/Tooltip/Tooltip.css

fix(Tooltip): fixed position

---

src/components/Sidebar/Sidebar.css
src/components/Sidebar/Sidebar.tsx

closes #2056
Исправлена проблема со всплытием кликов при hasOverlay=false

fix(SideBar): fix pointer-events

---

src/components/Tooltip/Tooltip.css
src/components/Tooltip/Tooltip.tsx
src/mixs/MixPopoverArrow/MixPopoverArrow.css
src/mixs/MixPopoverArrow/MixPopoverArrow.tsx
src/mixs/MixPopoverArrow/__stories__/MixPopoverArrow.stories.mdx
src/mixs/MixPopoverArrow/__stories__/examples/MixPopoverArrowExample/MixPopoverArrowExample.css
src/mixs/MixPopoverArrow/__stories__/examples/MixPopoverArrowExample/MixPopoverArrowExample.tsx

closes #1786
Добавлен миксин для стилизации стрелочки поповера

feat(MixPopoverArrow): add new mixin

---

src/components/ThemeToggler/ThemeToggler.tsx

fix(ThemeToggler): add reexport types

---

src/components/Calendar/Calendar.tsx
src/components/Collapse/Collapse.tsx
src/components/Combobox/Combobox.tsx
src/components/ContextMenuCanary/ContextMenuCanary.tsx
src/components/DatePickerCanary/DatePickerCanary.tsx
src/components/DateTimeCanary/DateTimeCanary.tsx
src/components/DragNDropField/DragNDropField.tsx
src/components/FileField/FileField.tsx
src/components/Pagination/Pagination.tsx
src/components/ProgressStepBarCanary/ProgressStepBarCanary.tsx
src/components/Radio/Radio.tsx
src/components/SliderCanary/SliderCanary.tsx
src/components/Switch/Switch.tsx
src/components/ThemeToggler/ThemeToggler.tsx
src/components/UserSelect/UserSelect.tsx

closes #2133
К EventInterceptor подключены следующие компоненты:
- `Calendar`
- `Collapse`
- `Combobox`
- `ContextMenuCanary`
- `DatePicker`
- `DateTime`
- `ContextMenuCanary`
- `DragNDropField`
- `FileField`
- `Pagination`
- `ProgressStepBarCanary`
- `Radio`
- `SliderCanary`
- `Switch`
- `ThemeToggler`
- `UserSelect`

feat(EventInterceptor): connect other components to EventInterceptor

---

src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__stories__/Checkbox.docs.mdx
src/components/Radio/Radio.tsx
src/components/Radio/__stories__/Radio.docs.mdx

closes #2090
dd new prop inputId to Checkbox and Radio

fix(Radio): add new prop inputId to Checkbox and Radio

---

src/components/ContextMenuCanary/ContextMenuLevels/ContextMenuLevels.tsx

fix(ContextMenu): fixed calculate zIndex

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy.yml

chore(deploy): add deploy automatization

---

.github/workflows/deploy.yml
src/components/Pagination/Pagination.tsx

fix(Pagination): conditional rendering moved to the bottom

---

src/components/ContextMenuCanary/__tests__/ContextMenu.test.tsx

test(ContextMenuCanary): add tests to ContextMenuCanary

---

.github/workflows/deploy.yml
package.json

chore(deploy): edit public path

---

src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
src/components/ContextMenuCanary/ContextMenuLevels/ContextMenuLevels.tsx

closes #2138
Пофиксил таймаут на закрытии вложенных уровней

fix(ContextMenuCanary): fix timeout on close inner levels

---

src/components/Button/__stories__/Button.docs.mdx
src/components/Button/__stories__/examples/ButtonExampleAdaptive/ButtonExampleAdaptive.tsx

Добавила в доку раздел про адаптивность.

docs(Button): add adaptive section

---

src/components/ContextMenuCanary/__stories__/ContextMenu.docs.mdx
src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick.tsx

Поправила парочку неработающий примеров.

docs(ContextMenu): fix examples

---

src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx

closes #2190
Решена проблема с ховер эффектом и индексами элементов

fix(SelectDropdown): fix bug with items index

---

src/hooks/useBreakpoints/useBreakpoints.ts

document.documentElement.clientWidth -> window.innerWidth
closes #2208

fix(useBreakpoints): fixed EventListener

---

.github/workflows/deploy.yml

chore(deploy): fix

---

src/components/Pagination/__stories__/Pagination.docs.mdx
src/components/Pagination/__stories__/examples/PaginationExample/PaginationExample.tsx

closes #2118
Добавила раздел про адаптивность и примерчик.

docs(Pagination): add adaptive section

---

src/components/Table/Table.tsx

fix(Table): fix lazyload

---

src/components/Responses/__stories__/Responses.docs.mdx
src/components/Responses/__stories__/examples/ResponsesExample/ResponsesExample.tsx
src/components/ResponsesExit/ResponsesExit.tsx

closes #2118
Добавила раздел про адаптивность, поправила опечатку.

docs(Responses): add adaptive section

---

src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleTwoFields/DatePickerExampleTwoFields.tsx

closes #2241
Добавила описание, как работают  свойства с типом  Range и один пример с иконками. 
Посмотрите, может, нужно больше примеров?

docs(DatePicker): add docs for type Range fields

---

src/components/Combobox/__stories__/Combobox.docs.mdx

closes #2115
Поменяла все примеры (вытащила из исходников). Теперь должно всё работать.
Заодно добавила в доку описание labelForNotFound и labelForCreate;

docs(Combobox): verify examples

---

src/components/Table/SelectedOptionsList/TableSelectedOptionsList.css

closes #1501
Добавлено свойство ellipsis к списку фильтров

fix(TableSelectedOptionsList): add ellipsis to filter list

---

src/components/DatePickerCanary/DatePickerTypeDateTimeRange/DatePickerTypeDateTimeRange.tsx
src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx

fix(DatePicker): fixed multiplicity on DatePicker type='date-time-range'

---

src/components/SnackBar/__stories__/SnackBar.docs.mdx
src/components/SnackBar/__stories__/examples/SnackBarExampleAdaptive/SnackBarExampleAdaptive.tsx

Добавила раздел про адаптивность, скопировала абзац из фигмы. И небольшой пример сделала снекбара в карточке.

docs(Snackbar): add adaptive section

---

src/components/Steps/__stories__/Steps.docs.mdx
src/components/Steps/__stories__/examples/ExampleStepsAdaptive/ExampleStepsAdaptive.tsx

closes #2118
Добавила в доку раздел про адаптивность (текст из фигмы + пример).

docs(Steps): add adaptive

---

src/components/Table/__stories__/Table.docs.mdx
src/components/Table/__stories__/examples/TableExampleAdaptive/TableExampleAdaptive.tsx

closes 2118
Добавила описание адаптивности и пару примеров.

docs(Table): add adaptive section

---

src/components/SliderCanary/useSliderStationing.ts

fix(Slider): fix detecting of active line

---

src/components/ContextMenuCanary/ContextMenu.css
src/components/ContextMenuCanary/ContextMenuCanary.tsx
src/components/ContextMenuCanary/__stories__/ContextMenu.stories.tsx
src/components/Popover/Popover.tsx
src/components/Popover/usePopoverReposition.ts

fix(Popover): fixed change position

---

src/components/Select/__tests__/Select.test.tsx
src/components/SelectComponents/SelectCreateButton/SelectCreateButton.tsx
src/components/SelectComponents/SelectLoader/SelectLoader.tsx
src/components/SelectComponents/__tests__/SelectCreateButton.test.tsx
src/components/SelectComponents/__tests__/SelectDropdown.test.tsx
src/components/SelectComponents/__tests__/SelectValueTag.test.tsx

test(Select): add tests to Select

---

src/hooks/useKeys/__tests__/useKeys.test.tsx

test(useKeys): add tests to useKeys

---

package.json
src/components/Combobox/helpers.ts
src/components/SliderCanary/SliderInput/SliderInput.tsx
src/components/TextField/TextField.css
src/components/TextField/TextField.tsx
src/components/TextField/__stories__/TextField.stories.tsx
src/components/TextField/helpers.ts
src/components/TextField/types.ts
yarn.lock

- add type password
- update react-testarea-autosize
- remove native required
closes #2351 #2350 #2354

feat(TextField): add type password and research

---

src/components/Table/Table.tsx
src/components/Table/__stories__/Table.stories.tsx
src/components/Table/__stories__/examples/TableExampleOnSortBy/TableExampleOnSortBy.tsx
src/components/Table/filtering.ts

fix(Table): add export SortByProps

---

builder/helpers/index.js

fix(fonts): fix export fonts

---

src/components/DragNDropField/DragNDropField.tsx
src/components/DragNDropField/DragNDropFieldContent/DragNDropFieldContent.tsx
src/components/DragNDropField/DragNDropFieldContent/__tests__/formatFileRequirements.ts
src/components/DragNDropField/DragNDropFieldContent/formatFileRequirements.ts
src/components/DragNDropField/__stories__/DragNDropField.docs.mdx
src/components/DragNDropField/__stories__/DragNDropField.stories.tsx
src/components/DragNDropField/getErrorsList.ts
src/components/DragNDropField/locale.ts
src/components/DragNDropField/types.ts

refactor(DragNDropField): refactor locale

---

src/components/Sidebar/Sidebar.tsx

fix(Sidebar): fixed rootClassName

---

src/components/DateTimeCanary/DateTimeTypeTime/helpers.ts

fix(DateTime): fixed multiplicity

---

src/components/ProgressLine/ProgressLine.css
src/components/ProgressLine/ProgressLine.tsx
src/components/ProgressLine/__stories__/ProgressLine.docs.mdx
src/components/ProgressLine/__stories__/ProgressLine.stories.tsx
src/components/ProgressLine/__stories__/examples/ProgressLineExampleMode/ProgressLineExampleMode.tsx
src/components/ProgressLine/__stories__/examples/ProgressLineExampleSize/ProgressLineExampleSize.tsx
src/components/ProgressLine/types.ts
src/components/ProgressSpin/ProgressSpin.tsx
src/components/ProgressSpin/__stories__/ProgressSpin.docs.mdx
src/components/ProgressSpin/__stories__/ProgressSpin.stories.tsx
src/components/ProgressSpin/__stories__/examples/ProgressSpinExampleProgress/ProgressSpinExampleProgress.tsx
src/components/ProgressSpin/__stories__/examples/ProgressSpinExampleSize/ProgressSpinExampleSize.tsx
src/components/ProgressSpin/__tests__/ProgressSpin.test.tsx

closes #2362
Добавлен новый компонент ProgressLine

feat(ProgressLine): add ProgressLine component

---

src/components/User/User.css

fix(User): fix word wrap

---

src/components/SliderCanary/SliderCanary.tsx
src/components/SliderCanary/SliderLine/SliderLine.css
src/components/SliderCanary/SliderPoint/SliderPoint.css
src/components/SliderCanary/useSlider/helper.ts
src/components/SliderCanary/useSlider/useSlider.ts
src/components/SliderCanary/useSliderStationing.ts

closes #2164
Исправлено поведение слайдера на очень маленьких и очень больших

fix(Slider): fix work of slider on a big and small values

---

src/components/TextField/TextField.tsx

fix(TextField): fixed disabled

---

.github/workflows/publish-stand.yaml
builder/copyPackageJsonForStoryBook.js

chore(storybook): add automatisation for publish stand

---

src/components/Card/Card.tsx
src/components/Card/__stories__/Card.docs.mdx
src/components/Card/__stories__/Card.stories.tsx
src/components/Card/__stories__/examples/CardExampleBorder/CardExampleBorder.tsx
src/mixs/MixCard/MixCard.css
src/mixs/MixCard/MixCard.tsx
src/mixs/MixCard/__stories__/MixCard.stories.mdx
src/mixs/MixCard/__stories__/examples/MixCardExampleBorder/MixCardExampleBorder.css
src/mixs/MixCard/__stories__/examples/MixCardExampleBorder/MixCardExampleBorder.tsx

closes #2121
Добавлены границы в миксин и компонент `Card`

feat(MixCard): add border prop to mixin

---

src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
src/components/DatePickerCanary/__stories__/examples/DatePickerExampleWithClearButton/DatePickerExampleWithClearButton.tsx

closes #2370
Добавила описание withClearButton и пример.

docs(DatePicker): add withClearButton description

---

src/components/Text/Text.css
src/components/Text/Text.tsx
src/components/Theme/_size/Theme_size_gpnDefault.css

feat(Fonts): add new font weight

---

CHANGELOG.md
src/components/Popover/__stories__/Popover.docs.mdx
src/components/Popover/__stories__/examples/PopoverExample/PopoverExample.css
src/components/Popover/__stories__/examples/PopoverExample/PopoverExample.tsx

closes #1131
Вытащила примеры из stories, добавила код примеров в доку. 
В задачке еще есть вот такое: В примере не указано, что popover нужно закрывать принудительно. Это точно нужно?

docs(Popover): change examples

---

src/components/Theme/__stories__/Theme.docs.mdx

closes #1315
Добавила описание теней в тему: для каких элементов и в каких случаях что используется.

docs(Theme): add shadows description

---

src/components/Button/__stories__/Button.docs.mdx
src/components/Button/__stories__/examples/ButtonExampleName/ButtonExampleName.tsx

Добавила пример слишком длинного и неудачно обрезанного текста на кнопке

docs(Button): add too big label example

---

src/components/Collapse/CollapseIcon/CollapseIcon.css

fix(Collapse): fix bug with color of icon on dark theme

---

src/components/Steps/StepsStep/StepsStep.tsx
src/components/StepsCanary/StepsStep/StepsStep.tsx

fix(Steps): fix crush with using google translate

---

src/components/Attachment/__stories__/Attachment.stories.tsx
src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
src/components/FieldGroup/__stories__/FieldGroup.stories.tsx
src/components/ProgressLine/__stories__/ProgressLine.stories.tsx
src/components/Skeleton/__stories__/Skeleton.stories.tsx
src/components/Text/__stories__/Text.stories.tsx
src/components/Tooltip/__stories__/Tooltip.stories.tsx

closes #2452
Исправила некорректные ссылки на фигму.

docs(components): fix figma links

---

src/components/Badge/Badge.css
src/components/Badge/Badge.tsx
src/components/Badge/__stories__/Badge.docs.mdx
src/components/Badge/__stories__/examples/BadgeExampleSize/BadgeExampleSize.tsx

feat(Badge): add  xs size

---

src/components/Modal/Modal.tsx
src/components/Sidebar/Sidebar.tsx

feat(Modal): add afterClose prop

---

src/components/ContextMenu/__stand__/ContextMenu.design.stand.mdx
src/components/ContextMenu/__stand__/ContextMenu.dev.stand.mdx
src/components/ContextMenu/__stand__/ContextMenu.image.svg
src/components/ContextMenu/__stand__/ContextMenu.stand.mdx
src/components/ContextMenu/__stand__/ContextMenu.stand.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleDefault/ContextMenuExampleDefault.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleLabel/ContextMenuExampleLabel.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSide/ContextMenuExampleSide.tsx
src/components/ContextMenu/__stories__/examples/ContextMenuExampleSize/ContextMenuExampleSize.tsx

Add Contextmenu documentation.

docs(custom): contextmenu

---

.github/workflows/deploy.yml

chore(gh-actions): add deploy from v4 branch

---

src/components/Table/RowsCollapse/TableRowsCollapse.tsx
src/components/Table/Table.tsx
src/components/Table/__stand__/Table.dev.stand.mdx
src/components/Table/__stand__/examples/TableExampleExpandable/TableExampleExpandable.tsx

feat(Table): add new props to table props and table row for expands rows

---

package.json

chore(deps): remove mdx-loader

---

src/components/SelectComponents/SelectItem/SelectItem.css

Исправлена высота элемента списка при пустой строке

fix(SelectItem): fix height of item with empty row

---

src/components/Layout/__stand__/Layout.variants.css
src/components/Layout/__stand__/examples/LayoutExampleAnchor/LayoutExampleAnchor.css
src/components/Layout/__stand__/examples/LayoutExampleBasic/LayoutExampleBasic.css
src/components/Layout/__stand__/examples/LayoutExampleDirection/LayoutExampleDirection.css
src/components/Layout/__stand__/examples/LayoutExampleDirection/LayoutExampleDirection.tsx
src/components/Layout/__stand__/examples/LayoutExampleFixed/LayoutExampleFixed.css
src/components/Layout/__stand__/examples/LayoutExampleRowFixed/LayoutExampleRowFixed.css

Добавлены бордюры в все примеры

docs(Layout): fix border on layout examples

---

src/components/ContextMenu/ContextMenuLevels/ContextMenuLevels.tsx
src/components/ContextMenu/types.ts

fix(ContextMenu): fixed reposition

---

src/components/Collapse/CollapseIcon/CollapseIcon.tsx
src/icons/Icon/Icon.tsx

feat(Icons): update types for usage icons from @consta/icons

---

src/components/Text/__stand__/examples/TextExampleAlign/TextExampleAlign.tsx
src/components/Text/__stand__/examples/TextExampleLineheight/TextExampleLineheight.tsx
src/components/Text/__stand__/examples/TextExampleSize/TextExampleSize.tsx
src/components/Text/__stand__/examples/TextExampleSpacing/TextExampleSpacing.tsx
src/components/Text/__stand__/examples/TextExampleView/TextExampleView.tsx
src/components/Text/__stand__/examples/TextExampleWeight/TextExampleWeight.tsx

fix(Text): fix quotes in the examples

---

src/hooks/useChoiceGroup/__tests__/useChoiceGroup.test.tsx
src/hooks/useChoiceGroup/useChoiceGroup.tsx

fix(useChoiceGroup): fix bug with false type variable

---

src/components/Table/Table.tsx
src/components/Table/helpers.ts

fix(Table): fix 'level' accessor

---

src/components/SnackBar/SnackBar.tsx
src/components/SnackBar/SnackBarItem/SnackBarItem.css
src/components/SnackBar/SnackBarItem/SnackBarItem.tsx
src/components/SnackBar/__stand__/SnackBar.dev.stand.mdx
src/components/SnackBar/__stand__/SnackBar.variants.tsx
src/components/SnackBar/__stand__/examples/SnackBarExampleForm/SnackBarExampleForm.tsx
src/components/SnackBar/types.ts

feat(SnackBar): add prop form

---

src/components/DateTime/DateTimeTypeDateTime/DateTimeTypeDateTime.css
src/components/DateTime/DateTimeTypeTime/DateTimeTypeTime.css

fix(DateTime): fix pading for date-time view

---

src/components/Collapse/Collapse.tsx
src/components/Collapse/CollapseIcon/CollapseIcon.tsx
src/components/Collapse/__stand__/Collapse.dev.stand.mdx
src/components/Collapse/__stand__/examples/CollapseExampleLabel/CollapseExampleLabel.css
src/components/Collapse/__stand__/examples/CollapseExampleLabel/CollapseExampleLabel.tsx
src/components/Collapse/types.ts
src/components/CollapseGroup/helpers.ts

feat(Collapse): rewrite label from string to ReactNode

---

src/components/Table/Cell/TableCell.css
src/components/Table/Table.tsx
src/components/Table/__mock__/data.mock.tsx
src/components/Table/__stand__/Table.dev.stand.mdx
src/components/Table/__stand__/Table.variants.tsx
src/components/Table/__stand__/examples/TableExampleRowSpan/TableExampleRowSpan.tsx
src/components/Table/__stand__/variants/TableVariantWithColSpan/TableVariantWithColSpan.tsx
src/components/Table/__stand__/variants/useVariants/useVariants.ts
src/components/Table/helpers.ts

feat(Table): add colSpan for columns and also add variants with examples

---

src/components/Table/RowsCollapse/TableRowsCollapse.tsx

fix(Table): fix bug with closing collapse rows

---

src/components/DatePicker/DatePicker.tsx

fix(DatePicker): fix labelPosition

---

src/components/CheckboxGroup/CheckboxGroup.css
src/components/CheckboxGroup/types.ts

feat(CheckboxGroup): add s and xs sizes

---

src/components/Skeleton/Skeleton.css
src/components/Skeleton/SkeletonBrick/SkeletonBrick.tsx
src/components/Skeleton/SkeletonCircle/SkeletonCircle.tsx
src/components/Skeleton/SkeletonText/SkeletonText.tsx

fix(Skeleton): fixed style

---

src/components/Table/Table.tsx

fix(Table): make a nested rows mergable witout parent row

---

src/components/Table/Table.tsx

fix(Table): fix ciolumn width detecting

---

src/components/TextField/TextField.css

fix(TextField): hide browser eye on type='password'

---

src/hooks/useComponentSize/__stand__/useComponentSize.stand.mdx
src/hooks/useComponentSize/__stand__/useComponentSize.stand.tsx

docs(useComponentSize): add documentation for useComponentSize hook and also add sandbox for it

---

src/components/ProgressStepBar/ProgressStepBarLine/ProgressStepBarLine.tsx
src/components/ProgressStepBar/__stand__/ProgressStepBar.variants.tsx
src/hooks/useScrollElements/useScrollElements.tsx

fix(ProgressStepBar): fix line width for activeIndex

---

src/components/SnackBar/SnackBar.css
src/components/SnackBar/SnackBar.tsx
src/components/UserSelect/UserSelectItem/UserSelectItem.css
src/components/UserSelect/UserSelectItem/UserSelectItem.tsx

fix(Snackbar, UserSelect): rewrite CssTransition to Transition

---

src/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
src/components/Breadcrumbs/BreadcrumbsMore/BreadcrumbsMore.tsx
src/components/ContextMenu/__stand__/ContextMenu.variants.tsx
src/components/ContextMenuDeprecated/__stand__/ContextMenu.dev.stand.mdx
src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleGroups/ContextMenuExampleGroups.tsx
src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSide/ContextMenuExampleSide.tsx
src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSimple/ContextMenuExampleSimple.tsx
src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSize/ContextMenuExampleSize.tsx
src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSubMenu/ContextMenuExampleSubMenu.tsx
src/components/Modal/__stand__/Modal.dev.stand.mdx
src/components/Modal/__stand__/examples/ModalExampleZIndex/ModalExampleZIndex.tsx
src/components/Popover/__stand__/Popover.variants.tsx
src/components/Tabs/MoreItems/TabsMoreItems.tsx
src/components/TabsDeprecated/MoreItems/TabsMoreItems.tsx
src/components/TextField/TextField.tsx
src/components/ThemeToggler/ThemeToggler.tsx
src/components/Tooltip/__stand__/examples/TooltipPosition/TooltipPosition.tsx
src/hooks/useFlag/useFlag.ts
src/mixs/MixPopoverAnimate/__stand__/MixPopoverAnimate.stand.mdx
src/mixs/MixPopoverAnimate/__stand__/examples/MixPopoverAnimateExample/MixPopoverAnimateExample.tsx
src/mixs/MixPopoverAnimate/__stories__/MixPopoverAnimate.stories.mdx
src/mixs/MixPopoverArrow/__stand__/MixPopoverArrow.stand.mdx
src/mixs/MixPopoverArrow/__stand__/examples/MixPopoverArrowExample/MixPopoverArrowExample.tsx
src/mixs/MixPopoverArrow/__stories__/MixPopoverArrow.stories.mdx

fix(useFlag): rewrite toogle to toggle

---

src/components/AutoCompleteCanary/__stand__/AutoComplete.stand.tsx
src/components/ListCanary/__stand__/List.stand.tsx
src/hooks/useChoiceGroupIndexed/__stand__/useChoiceGroupIndexed.stand.tsx
src/hooks/useComponentBreakpoints/__stand__/useComponentBreakpoints.stand.tsx

add links to sandbox for AutoComplete, List, useComponentBreakpoints, useChoiceGroupIndexed
#2856

docs(sandbox): add links to sandbox for a few components and hooks

---

src/components/Table/Table.tsx

fix(Table): fix bug with excluding in calculations previous state

---

src/components/AvatarGroup/AvatarGroup.css
src/components/AvatarGroup/AvatarGroup.tsx
src/components/AvatarGroup/__stand__/AvatarGroup.dev.stand.mdx
src/components/AvatarGroup/__stand__/AvatarGroup.stand.mdx
src/components/AvatarGroup/__stand__/AvatarGroup.variants.tsx
src/components/AvatarGroup/__stand__/examples/AvatarGroupExampleCount/AvatarGroupExampleCount.tsx
src/components/AvatarGroup/types.ts
src/components/Breadcrumbs/BreadcrumbsFitModeDropdown/BreadcrumbsFitModeDropdown.tsx
src/components/Breadcrumbs/useElements.ts
src/hooks/useHideElementsInLineCanary/__stand__/examples/ExampleUseHideElementsInLine/ExampleUseHideElementsInLine.css
src/hooks/useHideElementsInLineCanary/__stand__/examples/ExampleUseHideElementsInLine/ExampleUseHideElementsInLine.tsx
src/hooks/useHideElementsInLineCanary/__stand__/useHideElementsInLine.stand.mdx
src/hooks/useHideElementsInLineCanary/__stand__/useHideElementsInLine.stand.tsx
src/hooks/useHideElementsInLineCanary/helpers/getHiddenCount.ts
src/hooks/useHideElementsInLineCanary/index.ts
src/hooks/useHideElementsInLineCanary/useHideElementsInLineCanary.ts

feat(AvatarGroup): add visibleCount='auto'

---

src/mixs/MixFocus/MixFocus.css

feat(MixFocus): add vars

---

src/components/TextField/TextField.css

fix(TextField): fix bug with scroll on disabled textarea

---

src/components/Combobox/Combobox.tsx
src/components/SelectComponents/SelectItem/SelectItem.tsx
src/components/SelectComponents/SelectValueTag/SelectValueTag.css
src/components/SelectComponents/SelectValueTag/SelectValueTag.tsx
src/components/UserSelect/UserSelect.tsx
src/components/UserSelect/UserSelectItem/UserSelectItem.css
src/components/UserSelect/UserSelectValue/UserSelectValue.css
src/components/UserSelect/UserSelectValue/UserSelectValue.tsx
src/hooks/useSelect/useSelect.ts

fix(Selects): fix logic of choicing disabled items

---

src/components/DatePicker/DatePickerFieldTypeDate/DatePickerFieldTypeDate.tsx
src/components/DatePicker/DatePickerFieldTypeDate/helpers.ts
src/components/DatePicker/DatePickerFieldTypeDateTime/DatePickerFieldTypeDateTime.tsx
src/components/DatePicker/DatePickerFieldTypeDateTime/helpers.ts
src/components/DatePicker/DatePickerFieldTypeMonth/DatePickerFieldTypeMonth.tsx
src/components/DatePicker/DatePickerFieldTypeMonth/helpers.ts
src/components/DatePicker/DatePickerFieldTypeTime/DatePickerFieldTypeTime.tsx
src/components/DatePicker/DatePickerFieldTypeTime/helpers.ts
src/components/DatePicker/DatePickerFieldTypeYear/DatePickerFieldTypeYear.tsx
src/components/DatePicker/DatePickerFieldTypeYear/helpers.ts
src/components/TextField/__stand__/TextField.dev.stand.mdx
src/components/TextField/__stand__/examples/TextFieldExampleMask/TextFieldExampleMask.css
src/components/TextField/__stand__/examples/TextFieldExampleMask/TextFieldExampleMask.tsx
src/components/TextField/index.ts
src/components/TextField/useIMask.ts

docs(TextField): add examples with imask usage

---

src/components/ProgressStepBar/ProgressStepBar.css
src/components/ProgressStepBar/ProgressStepBar.tsx
src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.css
src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
src/components/ProgressStepBar/ProgressStepBarLine/ProgressStepBarLine.css
src/components/ProgressStepBar/ProgressStepBarLine/ProgressStepBarLine.tsx
src/components/ProgressStepBar/helpers.ts

feat(ProgressStepBar): rewrite line rendering and fix bug with hidden outline

---

src/components/ChoiceGroup/__stand__/ChoiceGroup.stand.tsx

docs(ChoiceGroup): update link to sandbox

---

src/components/EventInterceptor/propsHandlers/__tests__/useSelectEventsHandler.test.tsx
src/components/EventInterceptor/propsHandlers/useSelectEventsHandler.tsx

fix(EventInterceptor): fix logic of select handler

---

src/components/Combobox/__stand__/Combobox.variants.tsx
src/components/Combobox/helpers.ts
src/components/SelectComponents/Select.css
src/components/SelectComponents/SelectValueTag/SelectValueTag.tsx
src/components/TagBase/TagBase.css

feat(Combobox): add xs size

---

src/components/Slider/Slider.tsx
src/components/Slider/SliderInput/SliderInput.tsx
src/components/Slider/__stand__/Slider.dev.stand.mdx
src/components/Slider/__stand__/Slider.variants.tsx
src/components/Slider/__stand__/examples/SliderExampleContent/SliderExampleContent.tsx
src/components/Slider/__stand__/examples/SliderExampleRange/SliderExampleRange.tsx
src/components/Slider/helper.ts
src/components/Slider/useSlider/useSlider.ts

feat(Slider): add `'input'` for `rightSide`

---

src/components/Table/__stand__/Table.dev.stand.mdx

docs(Table): add accent on id in row

---

package.json
src/components/DateTime/DateTime.tsx
src/components/TextField/useIMask.ts
yarn.lock

fix(useIMask): fixed updateValue

---

src/components/TextField/TextField.css

feat(TextField): add margin to counter buttons for round forms

---

src/components/Combobox/Combobox.tsx
src/components/Combobox/helpers.ts
src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx

исправил тип dropdownRef, был не совсем верный тип

fix(Combobox): fixed type dropdownRef

---

src/components/Table/__stand__/variants/TableVariantWithBigData/TableVariantWithBigData.tsx

fix(Table): example fixed

---

src/stand/standConfig.ts

docs: edit description

---

src/hooks/useBreakpoints/__stand__/useBreakpoints.stand.mdx
src/hooks/useBreakpoints/addPrefix.ts
src/hooks/useBreakpoints/index.ts

добавиляет префикс для удобного использования в генерации класнейма

feat(useBreakpoints): added helper `addPrefix`

---

src/components/Combobox/__stand__/Combobox.dev.stand.mdx
src/components/Combobox/__stand__/examples/ComboboxExampleSearchValue/ComboboxExampleSearchValue.tsx
src/hooks/useSelect/useSelect.ts

fix(Combobox): fix update serchValue

---

src/components/TabsDeprecated/Tab/TabsTab.css
src/components/TabsDeprecated/Tab/TabsTab.tsx

fix(Tabs): fix styles break

---

src/components/DateTime/DateTimeTypeDate/DateTimeTypeDate.tsx
src/components/DateTime/DateTimeTypeMonth/DateTimeTypeMonth.tsx
src/components/DateTime/DateTimeTypeYear/DateTimeTypeYear.tsx

fix(DateTime): fig bug with useless props

---

src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx

fix(SelectDropown): fix labelForEmptyItems

---

src/components/Avatar/Avatar.css
src/components/User/User.css
src/components/User/User.tsx

fix(User): fix discrepancies between design and code

---

src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.css
src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx

fix(ProgressStepBar): fix discrepancies between design and code and also fix bugs

---

src/components/Checkbox/Checkbox.css

fix(Checkbox): fix arrow position

---

src/components/ListCanary/ListDivider/ListDivider.tsx
src/components/ListCanary/maps.ts

fix(List): fix discrepancies between desigh and code for list divider

---

src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.css
src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
src/components/DragNDropField/DragNDropField.tsx
src/components/Popover/Popover.css
src/components/Popover/Popover.tsx
src/components/Popover/index.ts
src/components/Slider/SliderPoint/SliderPoint.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/__stand__/Tooltip.dev.stand.mdx
src/components/Tooltip/__stand__/Tooltip.variants.tsx
src/utils/isRenderProp.ts

[ix(Popover): fixed twitching during positioning](https://github.com/consta-design-system/uikit/pull/3097/commits/8a2875ecab4172858c816e1a6bd4b827f847c575)
[refactor(ContextMenu): removed animation fix](https://github.com/consta-design-system/uikit/pull/3097/commits/fb13ea170180516ec8c1236fae7df224e4bcdda2)
[refactor(DragNDropField): removed isRenderProp](https://github.com/consta-design-system/uikit/pull/3097/commits/1650c36fddec6bb004a4c5ef9a7826fd81b30943)
[feat(Tooltip): add offset prop](https://github.com/consta-design-system/uikit/pull/3097/commits/2d344fe4208c1fc9f857e7fb6c6bffad9713ade9)
[fix(Slider): fix tooltip position](https://github.com/consta-design-system/uikit/pull/3097/commits/3d55ed255a60401d092824ec8c62fae7f7e8ec5c)

feat(Tooltip): add offset prop

---

src/components/Card/__stand__/Card.dev.stand.mdx

docs(Card): fix as description

---

src/components/ProgressStepBar/ProgressStepBarLine/ProgressStepBarLine.tsx

closes https://github.com/consta-design-system/uikit/issues/3093.
Добавил initial value для метода reduce в функции getActiveLineSize компонента ProgressStepBarLine

Fix/(ProgressStepBarLine): Reduce of empty array with no initial value

---

src/stand/standConfig.ts

docs(standConfig): add figmaUrl

---

src/components/Button/Button.css

feat(Button): update disabled styles

---

src/components/AutoCompleteCanary/useAutoComplete.ts

feat(AutoComplete): improvement searchFunction

---

src/components/Header/__stand__/Header.stand.tsx

docs(Header): marked as deprecated

---

src/components/Checkbox/Checkbox.css

fix(Checkbox): remove useless z-index

---

src/hocs/withTooltip/__stand__/examples/WithTooltipExampleMode/WithTooltipExampleMode.tsx
src/hocs/withTooltip/__stand__/examples/WithTooltipExampleProps/WithTooltipExampleProps.tsx
src/hocs/withTooltip/__stand__/examples/WithTooltipExampleSize/WithTooltipExampleSize.tsx
src/hocs/withTooltip/__stand__/examples/WithTooltipExampleText/WithTooltipExampleText.tsx
src/hocs/withTooltip/withTooltip.tsx

fix(withTooltip): fix types

---

src/components/TextField/TextField.tsx

fix(TextField): fix onChange params

---

src/components/Text/Text.css
src/components/Text/Text.tsx
src/components/Text/__stand__/Text.dev.stand.mdx

feat(Text): add new colors

---

src/components/Combobox/Combobox.tsx
src/components/DatePicker/DatePickerFieldTypeDateRange/DatePickerFieldTypeDateRange.tsx
src/components/DatePicker/DatePickerFieldTypeDateTimeRange/DatePickerFieldTypeDateTimeRange.tsx
src/components/DatePicker/DatePickerFieldTypeMonthRange/DatePickerFieldTypeMonthRange.tsx
src/components/DatePicker/DatePickerFieldTypeYearRange/DatePickerFieldTypeYearRange.tsx
src/components/Select/Select.tsx
src/components/SelectComponents/SelectContainer/SelectContainer.tsx
src/components/TextField/TextField.tsx
src/components/UserSelect/UserSelect.tsx

feat(FieldLabel): change render to as and add htmlFor

---

src/components/ListCanary/__stand__/List.stand.mdx

docs(List): fix import example

---

src/hooks/useSelect/useSelect.ts

fix(useSelect): open dropdown when typing

---

src/components/Steps/Steps.tsx
src/components/Steps/StepsStep/StepsStep.css
src/components/Steps/StepsStep/StepsStep.tsx
src/components/Steps/__stand__/Steps.dev.stand.mdx
src/components/Steps/__stand__/examples/ExampleStepsSize/ExampleStepsSize.tsx
src/components/Steps/__tests__/Steps.test.tsx
src/components/Steps/types.ts

fix(Steps): fix discrepancies between design and code

---

src/components/Table/__stand__/Table.dev.stand.mdx
src/components/Table/__stand__/Table.use.stand.mdx
src/components/Table/__stand__/use/Table.use.css
src/components/Table/__stand__/use/TableUseWithBigData/TableUseWithBigData.tsx
src/components/Table/__stand__/use/TableUseWithCustomFilters/TableUseWithCustomFilters.tsx
src/components/Table/__stand__/use/TableUseWithCustomRowsPlaceholder/TableUseWithCustomRowsPlaceholder.tsx
src/components/Table/__stand__/use/TableUseWithCustomTagLabelFunction/TableUseWithCustomTagLabelFunction.tsx
src/components/Table/__stand__/use/TableUseWithGetAdditionalClassName/TableUseWithGetAdditionalClassName.tsx
src/components/Table/__stand__/use/TableUseWithHandleCellClickExample/TableUseWithHandleCellClickExample.tsx
src/components/Table/__stand__/use/TableUseWithHiddenColumn/TableUseWithHiddenColumn.tsx
src/components/Table/__stand__/use/TableUseWithIcon/TableUseWithIcon.tsx
src/components/Table/__stand__/use/TableUseWithMergedByCustomCallbackCells/TableUseWithMergedByCustomCallbackCells.tsx
src/components/Table/__stand__/use/TableUseWithRowActions/TableUseWithRowActions.tsx
src/components/Table/__stand__/use/TableUseWithStickyColumn/TableUseWithStickyColumn.tsx
src/components/Table/__stand__/use/TableUseWithStickyHeader/TableUseWithStickyHeader.tsx

docs(Table): replace code examples to how to use

---

src/components/AutoCompleteCanary/useAutoComplete.ts
src/components/ContextMenu/ContextMenuLevels/ContextMenuLevels.tsx
src/components/ContextMenuDeprecated/ContextMenuDeprecated.tsx

fix(ContextMenu): fixed an unnecessary call onClickOutside

---

src/components/Button/Button.css

fix(Button): fix border for secondary view

---

src/components/TextField/TextField.tsx

fix(TextField): fix value checking

---

src/components/Collapse/Collapse.css

fix(Collapse): fix collapse height

---

src/components/AutoCompleteCanary/useAutoComplete.ts

bugfix: fix Tab two times when enter own custom  value

---

src/components/ProgressStepBar/ProgressStepBar.tsx
src/components/ProgressStepBar/helpers.ts

fix(ProgressStepBar): fix refs problem

---

src/components/Badge/Badge.css
src/components/Badge/Badge.tsx
src/components/Badge/__stand__/Badge.variants.tsx

feat(Badge): add counter mod

---

src/components/Switch/__stand__/Switch.dev.stand.mdx

docs(Switch): fix example

---

src/components/Button/Button.css
src/components/Button/Button.tsx

fix(Button): fix disabled mode

---

src/components/ListCanary/ListItemGrid/ListItemGrid.tsx

fix(List): fixed render undefined in renderSlot

---

src/components/BookmarkTabsCanary/BookmarkTabsCanary.tsx
src/components/BookmarkTabsCanary/BookmarkTabsTab/BookmarkTabsTab.tsx
src/components/ThemeToggler/ThemeToggler.tsx

fix(Button): property type set to all places

---

src/components/Combobox/Combobox.tsx
src/components/ComboboxCanary/ComboboxCanary.tsx
src/components/Select/Select.tsx
src/components/SelectCanary/SelectCanary.tsx
src/components/UserSelect/UserSelect.tsx
src/components/UserSelectCanary/UserSelectCanary.tsx

fix(Selects): fix render numbers value

---

src/mixs/MixFlex/MixFlex.css
src/mixs/MixFlex/MixFlex.ts
src/mixs/MixFlex/__stand__/MixFlex.stand.mdx
src/mixs/MixFlex/__stand__/MixFlex.stand.tsx
src/mixs/MixFlex/__stand__/examples/MixFlexExample/MixFlexExample.css
src/mixs/MixFlex/__stand__/examples/MixFlexExample/MixFlexExample.tsx
src/mixs/MixFlex/index.ts

feat(MixFlex): add new mixin

---

src/components/Responses/Responses.tsx
src/components/Responses/createResponses.tsx
src/components/Responses403/Responses403.tsx
src/components/Responses403/index.ts
src/components/Responses404/Responses404.tsx
src/components/Responses404/index.ts
src/components/Responses500/Responses500.tsx
src/components/Responses500/index.ts
src/components/Responses503/Responses503.tsx
src/components/Responses503/index.ts
src/components/ResponsesConnectionError/ResponsesConnectionError.tsx
src/components/ResponsesConnectionError/index.ts
src/components/ResponsesDeleted/ResponsesDeleted.tsx
src/components/ResponsesDeleted/index.ts
src/components/ResponsesEmptyBox/ResponsesEmptyBox.tsx
src/components/ResponsesEmptyBox/index.ts
src/components/ResponsesEmptyPockets/ResponsesEmptyPockets.tsx
src/components/ResponsesEmptyPockets/index.ts
src/components/ResponsesExit/ResponsesExit.tsx
src/components/ResponsesNothingFound/ResponsesNothingFound.tsx
src/components/ResponsesNothingFound/index.ts
src/components/ResponsesSuccess/ResponsesSuccess.tsx
src/components/ResponsesSuccess/index.ts

feat(Responses): added images reexports

---

src/hocs/withTooltip/__tests__/withTooltip.test.tsx
src/hocs/withTooltip/withTooltip.tsx

chore(withTooltip): update tests

---

src/components/Combobox/__stand__/Combobox.dev.stand.mdx
src/components/Combobox/__stand__/examples/ComboboxExampleSearchValue/ComboboxExampleSearchValue.tsx
src/components/ComboboxCanary/__stand__/Combobox.dev.stand.mdx
src/components/ComboboxCanary/__stand__/examples/ComboboxExampleSearchValue/ComboboxExampleSearchValue.tsx

fix(Combobox): fix examples with search value

---

src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
src/components/DatePicker/__stand__/examples/DatePickerExampleOnError/DatePickerExampleOnError.tsx
src/components/DragNDropField/DragNDropFieldTooltip/DragNDropFieldTooltip.tsx
src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
src/components/Slider/SliderPoint/SliderPoint.tsx
src/components/TooltipCanary/TooltipCanary.tsx
src/components/TooltipCanary/types.ts
src/hocs/withTooltip/withTooltip.tsx

feat(TooltipCanary): replace a old tooltip with new canary version

---

src/components/Responses/Responses.css
src/components/Responses/Responses.tsx
src/components/Responses403/Responses403.tsx
src/components/Responses500/Responses500.tsx
src/components/Responses503/Responses503.tsx
src/components/ResponsesConnectionError/ResponsesConnectionError.tsx
src/components/ResponsesDeleted/ResponsesDeleted.tsx

fix(Responses): fix discrepancies

---

src/components/Combobox/Combobox.tsx
src/components/Combobox/helpers.ts
src/components/ComboboxCanary/ComboboxCanary.tsx
src/components/ComboboxCanary/helpers.ts
src/components/Select/Select.tsx
src/components/Select/helpers.ts
src/components/SelectCanary/SelectCanary.tsx
src/components/SelectCanary/helpers.ts
src/components/SelectComponents/Select.css
src/components/SelectComponentsCanary/Select.css
src/components/UserSelect/UserSelect.tsx
src/components/UserSelect/helpers.ts
src/components/UserSelectCanary/UserSelectCanary.tsx
src/components/UserSelectCanary/helpers.ts

feat(Selects): change clear icon and sizes

---

.eslintrc.js
package.json
src/components/ChoiceGroup/types.ts
src/components/ChoiceGroupDeprecated/ChoiceGroupDeprecated.tsx
src/components/DateTime/helpers/getHandleSelectDate.ts
src/components/DateTime/helpers/types.ts
yarn.lock

chore(eslint): add ascii plugin and rules

---

src/components/DragNDropField/DragNDropFieldTooltip/DragNDropFieldTooltip.tsx

Тутлип с ошибкой всегда показывался

fix(DragNDropField): fixed DragNDropFieldTooltip

---

src/components/Tabs/FitModeDropdownWrapper/TabsFitModeDropdownWrapper.tsx
src/components/Tabs/FitModeScrollWrapper/TabsFitModeScrollWrapper.tsx
src/components/Tabs/MoreItems/TabsMoreItems.css
src/components/Tabs/MoreItems/TabsMoreItems.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/types.ts

fix(Tabs): fix keyboard navigation

---

src/hooks/useResizableContentCanary/__stand__/useResizableContent.stand.mdx
src/hooks/useStyleProps/__stand__/useStyleProps.stand.mdx

Docs(): fix typos

---

src/components/EventInterceptor/propsHandlers/useCheckboxEventsHandler.tsx

fix(EventInterceptor): fix Checkbox events handler

---

package.json
src/components/TextField/TextField.css
src/components/TextField/TextField.tsx
src/components/TextField/__stand__/TextField.variants.tsx
src/components/TextField/helpers.ts
src/components/TextField/types.ts
yarn.lock

fix(TextField): fixed rightSide and clearButton

---

src/components/SelectComponents/Select.css

fix(Combobox): fixed align ClearButton

---

.github/workflows/deploy.yml
.github/workflows/tests.yml
package.json
yarn.lock

chore(deps): install-peers-cli

---

src/components/FieldLabel/FieldLabel.tsx

fix icon position (left -> right), fix margin
fix #3462

fix(FieldLabel): fix icon position

---

src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
src/components/DatePicker/__stand__/examples/DatePickerExampleOnError/DatePickerExampleOnError.tsx
src/components/TextField/TextField.tsx

fix(DatePicker): typo corrected

---

src/components/Tooltip/__stand__/Tooltip.dev.stand.mdx
src/components/Tooltip/__stand__/Tooltip.stand.mdx

Поправила код для импорта в соответствии с изменениями в мажорной версии

docs: fix-tooltip

---

src/components/Theme/__stand__/Theme.dev.stand.mdx
src/components/Theme/__stand__/examples/ThemeExampleRoot/ThemeExampleRoot.tsx

docs(Theme): fixed example

---

src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/DatePickerAdditionalControls/DatePickerAdditionalControls.tsx
src/components/DatePicker/DatePickerDropdown/DatePickerDropdown.tsx
src/components/DatePicker/DatePickerFieldTypeDate/DatePickerFieldTypeDate.tsx
src/components/DatePicker/DatePickerFieldTypeDateRange/DatePickerFieldTypeDateRange.tsx
src/components/DatePicker/DatePickerFieldTypeDateTime/DatePickerFieldTypeDateTime.tsx
src/components/DatePicker/DatePickerFieldTypeDateTimeRange/DatePickerFieldTypeDateTimeRange.tsx
src/components/DatePicker/DatePickerFieldTypeMonthRange/DatePickerFieldTypeMonthRange.tsx
src/components/DatePicker/DatePickerFieldTypeTime/DatePickerFieldTypeTime.tsx
src/components/DatePicker/DatePickerFieldTypeYear/DatePickerFieldTypeYear.tsx
src/components/DatePicker/DatePickerFieldTypeYearRange/DatePickerFieldTypeYearRange.tsx
src/components/DatePicker/DatePickerTypeDate/DatePickerTypeDate.tsx
src/components/DatePicker/DatePickerTypeDateRange/DatePickerTypeDateRange.tsx
src/components/DatePicker/DatePickerTypeDateTime/DatePickerTypeDateTime.tsx
src/components/DatePicker/DatePickerTypeDateTimeRange/DatePickerTypeDateTimeRange.tsx
src/components/DatePicker/DatePickerTypeMonth/DatePickerTypeMonth.tsx
src/components/DatePicker/DatePickerTypeMonthRange/DatePickerTypeMonthRange.tsx
src/components/DatePicker/DatePickerTypeTime/DatePickerTypeTime.tsx
src/components/DatePicker/DatePickerTypeYear/DatePickerTypeYear.tsx
src/components/DatePicker/DatePickerTypeYearRange/DatePickerTypeYearRange.tsx

fix(DatePicker): fixed inputRef

---

src/components/Slider/useSlider/helper.ts
src/components/Slider/useSlider/useSlider.ts

fix(Slider): fixed onChange event when mounting a component

---

src/components/Chips/Chips.tsx
src/components/Chips/ChipsChoice/ChipsChoice.tsx
src/components/Chips/ChipsChoice/types.ts
src/components/Chips/ChipsItem/ChipsItem.css
src/components/Chips/ChipsItem/ChipsItem.tsx
src/components/Chips/__mocks__/mock.data.ts
src/components/Chips/__stand__/Chips.dev.stand.mdx
src/components/Chips/__stand__/variants/ChipsChoiceVariants.tsx
src/components/Chips/__stand__/variants/ChipsItemVariant.tsx
src/components/Chips/__stand__/variants/ChipsVariants.tsx
src/components/Chips/helpers.ts
src/components/Chips/types.ts

re #3486
add disabled and getItemDisabled props and styles

feat(Chips): add disabled and getItemDisabled props and styles

---

src/components/Switch/Switch.css

fix(Swith): fixed align circle

---

src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/ChoiceGroup/Item/ChoiceGroup-Item.tsx

feat(ChoiceGroup): add title for truncate

---

src/components/UserSelect/UserSelectItem/UserSelectItem.css
src/components/UserSelect/UserSelectItem/UserSelectItem.tsx

feat(UserSelect): edit disable style

---

src/components/Badge/Badge.css
src/components/Badge/Badge.tsx
src/components/Badge/__stand__/Badge.variants.tsx

fix(Badge): fixed spaces

---

src/components/TextField/TextField.tsx

fix(TextField): fixed ClearButton for type number

---

src/components/Table/__stand__/Table.dev.stand.mdx

fix(Table): fix docs

---

src/components/Button/Button.tsx

fix(button): add missing html form attribute

---

src/components/DateTime/__tests__/DateTime_type_date.test.tsx
src/components/DateTime/helpers/useCurrentVisibleDate.ts

Теперь даты по умолчанию отображаются не меньше минимальной, если задана, и не больше максимальной, если задана. Причем выбирается минимум и максимум, если текущая дата меньше минимальной или больше максимальной соответственно.
Добавлены тесты
fixes #3644

fix(date-time): Добавлено округление в рамках min-max

---

src/components/Checkbox/Checkbox.css
src/components/Radio/Radio.css
src/components/Switch/Switch.css
yarn.lock

Update checkmarks size, offset, line height
re #3591

feat(Switch/Checkbox/Radio): update checkmarks proportions

---

src/components/DatePicker/DatePickerMixRangeField/DatePickerMixRangeField.css
src/components/SelectComponents/Select.css
src/components/TextField/TextField.css

Судя по фигме, их быть не должно во всех компонентах, в которых он раньше был.
Не стал исправлять SelectDeprecated: нужно ли?
fixes #3658

fix(caption): Убран левый отступ в компонентах

---

src/components/AutoComplete/useAutoComplete.ts

Теперь теперь изменение value ни как не влияет на состояние дропдауна открыт/закрыт 
closes #3689

fix(AutoComplite): removed dependence on value

---

src/components/DatePicker/helpers.ts

fix(DatePicker): fixed nulling of value

---

src/components/DatePicker/helpers.ts

fix(DatePicker): sync stringValue

---

src/components/SelectComponents/useSelect/useSelect.ts
src/components/UserSelect/__stand__/UserSelect.dev.stand.mdx
src/components/UserSelect/__stand__/examples/UserSelectExampleMailInput/UserSelectExampleMailInput.tsx
src/components/UserSelect/helpers.ts

Изменил пример на более реальный

docs(UserSelect): adit example for create

---

src/components/Tabs/TabsFitModeDropdownWrapper/useFittingItems.ts

fix(tabs): fix add tab from last selected

---

src/hocs/withTooltip/withTooltip.tsx

fix(withTooltip): typo

---

src/components/Combobox/__stand__/Combobox.dev.stand.mdx
src/components/Combobox/__stand__/examples/ComboboxExampleOpenByFocus/ComboboxExampleOpenByFocus.tsx

docs(Combobox): add example: opening by focus

---

src/components/TextField/TextField.tsx
src/components/TextField/helpers.ts

fix(TextField): fixed arrowUp and arrowDown handlers

---

src/components/Theme/_size/Theme_size_gpnDefault.css

fix(Theme): --font-weight-text-extralight value

---

src/components/ChoiceGroup/ChoiceGroup.css
src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/ChoiceGroup/Item/ChoiceGroup-Item.tsx

fix(ChoiceGroup): remove `pointer-events: none;` on ChoiceGroup-Item

---

src/components/Slider/useSlider/useSlider.ts

fix(Slider): fixed onChande on input

---

src/components/Text/Text.css
src/components/Text/Text.tsx
src/components/Theme/_size/Theme_size_gpnDefault.css

feat(Text): add _weight_extralight and _weight_extrabold

---

src/components/Table/__stand__/Table.dev.stand.mdx
src/components/Table/__stand__/Table.stand.mdx
src/components/Table/__stand__/Table.stand.tsx
src/components/Table/__stand__/Table.use.stand.mdx

feat(Table): mark us deprecated

---

src/components/ProgressStepBar/ProgressStepBar.tsx
src/components/ProgressStepBar/helpers.ts
src/hooks/useScrollElements/useScrollElements.tsx

fix(ProgressStepBar): add validate activeStepIndex

---

src/components/DatePicker/DatePickerDropdown/DatePickerDropdown.tsx
src/components/DatePicker/DatePickerTypeDate/DatePickerTypeDate.tsx
src/components/DatePicker/DatePickerTypeDateRange/DatePickerTypeDateRange.tsx
src/components/DatePicker/DatePickerTypeDateTime/DatePickerTypeDateTime.tsx
src/components/DatePicker/DatePickerTypeDateTimeRange/DatePickerTypeDateTimeRange.tsx
src/components/DatePicker/DatePickerTypeMonth/DatePickerTypeMonth.tsx
src/components/DatePicker/DatePickerTypeMonthRange/DatePickerTypeMonthRange.tsx
src/components/DatePicker/DatePickerTypeTime/DatePickerTypeTime.tsx
src/components/DatePicker/DatePickerTypeYear/DatePickerTypeYear.tsx
src/components/DatePicker/DatePickerTypeYearRange/DatePickerTypeYearRange.tsx
src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
src/components/DatePicker/__stand__/examples/DatePickerExampleDisableDates/DatePickerExampleDisableDates.tsx
src/components/DatePicker/__stand__/examples/DatePickerExampleType/DatePickerExampleType.tsx
src/components/DatePicker/types.ts

feat(DatePicker): add disableDates

---

src/components/Badge/Badge.css
src/components/Badge/Badge.tsx
src/components/Badge/__stand__/Badge.dev.stand.mdx
src/components/Badge/__stand__/Badge.variants.tsx
src/components/Badge/__stand__/examples/BadgeExampleStatus/BadgeExampleStatus.tsx
src/components/Badge/__tests__/Badge.test.tsx
src/components/Badge/cn.ts
src/components/Badge/guardStatus.ts
src/components/Badge/index.ts
src/components/Badge/maps.ts
src/components/Badge/types.ts
src/components/BadgeGroup/BadgeGroup.tsx
src/components/BadgeGroup/__stand__/BadgeGroup.dev.stand.mdx
src/components/BadgeGroup/__stand__/examples/BadgeGroupExampleBasic/BadgeGroupExampleBasic.tsx
src/components/BadgeGroup/__stand__/examples/BadgeGroupExampleFitMode/BadgeGroupExampleFitMode.tsx
src/components/BadgeGroup/__stand__/examples/BadgeGroupExampleForm/BadgeGroupExampleForm.tsx
src/components/BadgeGroup/__stand__/examples/BadgeGroupExampleItems/BadgeGroupExampleItems.tsx
src/components/BadgeGroup/__stand__/examples/BadgeGroupExampleSize/BadgeGroupExampleSize.tsx
src/components/BadgeGroup/types.ts
src/components/Chips/__stand__/Chips.dev.stand.mdx
src/components/Chips/__stand__/examples/ChipsChoiceExample/ChipsChoiceExample.tsx
src/components/Chips/__stand__/examples/ChipsSimpleExample/ChipsSimpleExample.tsx
src/components/Chips/types.ts

feat(Badge): add _view_pinted and _status_disabled

---

src/components/Slider/useSlider/useSlider.ts

Добавил проверку на проп `disabled` в обработчике `onSliderClick`.
closes #3464

fix(useSlider): fix value changing after click with disabled prop

---

src/components/Steps/StepsStep/StepsStep.tsx
src/components/Steps/__tests__/Steps.test.tsx

Закрывает #3813. Добавил обертку для порядкового номера шага.

feat(StepsStep): add wrapper to step index

---

src/components/Informer/Informer.css

fix(Informer): fixed icon position

---

src/components/Tag/Tag.tsx
src/components/Tag/__stand__/Tag.dev.stand.mdx
src/components/Tag/__stand__/Tag.variants.tsx
src/components/Tag/__tests__/Tag.test.tsx
src/components/TagBase/TagBase.css
src/components/TagBase/TagBase.tsx

closes #3547. Добавил новый проп `disabled` в компоненте `Tag`

feat(Tag): add disabled prop

---

src/components/DatePicker/DatePickerTypeDateRange/DatePickerTypeDateRange.tsx
src/components/DatePicker/DatePickerTypeDateTime/DatePickerTypeDateTime.tsx
src/components/DatePicker/DatePickerTypeDateTimeRange/DatePickerTypeDateTimeRange.tsx
src/components/DatePicker/DatePickerTypeMonthRange/DatePickerTypeMonthRange.tsx
src/components/DatePicker/DatePickerTypeYearRange/DatePickerTypeYearRange.tsx
src/components/DatePicker/__stand__/DatePicker.variants.css
src/components/DatePicker/__stand__/DatePicker.variants.tsx
src/components/DatePicker/timeForMap.ts
src/components/DateTime/helpers/useCurrentVisibleDate.ts

проблема была в конкуренции useEffect
closes #3838

fix(DataPicker): fixed visited date

---

.github/workflows/tests.yml

chore(cspell): add  --no-progress flag

---

src/components/ContextMenu/ContextMenuWrapper/ContextMenuWrapper.tsx

fix(Transition): fixed findDOMNode is not a function in react 19

---

src/components/Attachment/Attachment.tsx

fix(Attachment): fixes attachment actions key

---

src/components/Avatar/__tests__/Avatar.test.tsx
src/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx
src/components/FieldComponents/FieldArrayValueInlineControl/FieldArrayValueInlineControl.css
src/components/FieldComponents/FieldArrayValueInlineControl/FieldArrayValueInlineControl.tsx
src/components/Popover/Popover.tsx
src/components/SelectCanary/SelectDropdown/SelectDropdown.tsx
src/components/SelectCanary/SelectInput/SelectInput.css
src/components/SelectCanary/SelectInput/SelectInput.tsx
src/components/SelectCanary/SelectMultiple/SelectMultiple.css
src/components/SelectCanary/SelectMultiple/SelectMultiple.tsx
src/components/SelectCanary/SelectMultipleValue/SelectMultipleValue.css
src/components/SelectCanary/SelectMultipleValue/SelectMultipleValue.tsx
src/components/SelectCanary/SelectMultipleValue/index.ts
src/components/SelectCanary/SelectSingle/SelectSingle.tsx
src/components/SelectCanary/useSelect/useSelect.ts
src/components/SelectComponents/useSelect/useSelect.ts
src/utils/state/useSendToAtom/useSendToAtom.ts

fix(Select, Combobox): fixed focus state in firefox

---

src/components/ThemeToggler/ThemeToggler.tsx

Добавлена анимация смены иконок

feat(ThemeToggler): added animation for switching icons

---

src/components/FieldComponents/FieldWrapper/helpers.ts

fix(FieldWrapper): change gap for size=s

---

src/components/Badge/__tests__/Badge.test.tsx
src/components/Badge/__tests__/getBgColor.test.ts
src/components/Badge/__tests__/getBorderColor.test.ts
src/components/Badge/__tests__/getDegreeMixing.test.ts
src/components/Badge/__tests__/getHorizontalPadding.test.ts
src/components/Badge/__tests__/getMinifiedBorderSize.test.ts
src/components/Badge/__tests__/getSize.test.ts
src/components/Badge/__tests__/getTextColor.test.ts
src/components/Badge/__tests__/getTextSize.test.ts

test(Badge): add tests

---

src/components/BadgeGroup/__tests__/BadgeGroup.test.tsx
src/components/Breadcrumbs/BreadcrumbsFitModeScroll/BreadcrumbsFitModeScroll.tsx
src/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
src/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx
src/components/Breadcrumbs/helpers.ts
src/components/Breadcrumbs/types.ts

test(Breadcrumbs): add tests

---

src/components/Button/__tests__/Button.test.tsx
src/components/Card/Card.tsx
src/components/Card/__tests__/Card.test.tsx

test(Button): updating tests

---

src/components/Radio/__tests__/Radio.test.tsx

test(Radio): update tests

---

src/components/ContextMenu/ContextMenuLevels/ContextMenuLevels.tsx
src/utils/setRef.ts

fix(ContextMenu): fixed outside clicks

---

src/components/FieldComponents/FieldArrayValueInlineControl/FieldArrayValueInlineControl.tsx
src/components/FieldComponents/FieldControlLayout/FieldControlLayout.css
src/components/TextFieldCanary/TextFieldTypeTextArray/TextFieldTypeTextArray.css
src/components/TextFieldCanary/TextFieldTypeTextArray/TextFieldTypeTextArray.tsx

fix(TextFieldCanary): fixed calculate width

---

src/components/Pagination/__stand__/examples/PaginationExample/PaginationExample.tsx
src/components/Pagination/__stand__/examples/PaginationExampleArrows/PaginationExampleArrows.tsx
src/components/Pagination/__stand__/examples/PaginationExampleFirstLastItem/PaginationExampleFirstLastItem.tsx
src/components/Pagination/__stand__/examples/PaginationExampleForm/PaginationExampleForm.tsx
src/components/Pagination/__stand__/examples/PaginationExampleHotKeys/PaginationExampleHotKeys.tsx
src/components/Pagination/__stand__/examples/PaginationExampleOuterMostArrows/PaginationExampleOuterMostArrows.tsx
src/components/Pagination/__stand__/examples/PaginationExampleSize/PaginationExampleSize.tsx
src/components/Pagination/__stand__/examples/PaginationExampleType/PaginationExampleType.tsx
src/components/Pagination/__stand__/examples/PaginationExampleVisibleCount/PaginationExampleVisibleCount.tsx

docs(Pagination): fixed examples

---

src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
src/components/ProgressStepBar/__tests__/ProgressStepBar.test.tsx
src/components/ProgressStepBar/__tests__/ProgressStepBarItem.test.tsx
src/components/ProgressStepBar/helpers.ts

closes #4052.
Поправил функцию расчета размера для линии между шагами.
Добавил тесты для ProgressStepBar

fix(ProgressStepBar): fix line width for 2 steps
