- src/components/Input/index.tsx
Невозможно передать **type** через пропсы. К примеру нужно прокинуть `type="password"`
> Remove type from Input component

- package.json
- yarn.lock
В данный момент eslint, который используется в react-scripts, используется в качестве основной зависимости, и перезаписывает eslint, установленный в проекте, который использует ui-kt в качестве зависимости.
> Переместить react-scripts в devDependencies

- package.json
- tsconfig.json
- yarn.lock
Добавил генерацию типов - теперь в библиотеке есть удобный автокомплит импортов, их свойств, ну и не надо заниматься дублированием деклараций в каждом из проектов, куда импортится ui-kit.
Подъем версии TS обеспечивает совместную работу опций declaration и allowJs/isolatedModules.
> добавляет типизацию для использования в сторонних проектах

- package.json
Чтобы при выполнении `npm publish` автоматически запускалась установка пакетов и сборка
> chore: build package before publish

- src/components/Button/Button.css
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- yarn.lock
Тесты для компонента Button уже были написаны в https://github.com/gpn-prototypes/ui-kit/pull/95
Я добавил тесты для состояния loading и добавил свил свойство `disabled` для `button`.
В стилях убрал селектор по `:disabled` - он не играет никакой роли в данном случае, но с ним общая конструкция выглядит только более многословно
> Написать тесты для компонента Button

- src/icons/Icon/Icon.tsx
Сейчас для обёртки используется тэг `div`, что приводит к тому что внутри кнопок, строчных элементов размещается `div`.
Данный фикс заменяет `div` на `span`
> Заменить тег обёртки компонента Icon

- src/components/TextField/TextField.css
Этот фикс исправляет стиль при автозаполнении
> Исправить стиль состояния textfield при автозаполнении браузером

- src/components/SnackBar/Item/SnackBar-Item.tsx
- src/components/SnackBar/SnackBar.test.tsx
- src/components/SnackBar/Timer/SnackBar-Timer.tsx
- src/utils/useTimer.ts
Исправлены ошибки бесконечного рендера тамера
Исправленна ошибка невозможности сменить состояние тамера после того как он был удален из виртуладом, Изменен Api хука useTimer на более стабильный. Теперь `timeIsOver` не колбеком при инициализации таймера, а не посредственно в значениях хука 
closes #187
> fix(SnackBar-Timer): fixed bugs related to infinite component rendering

- src/components/Attach/stories/examples/AttachExampleError/AttachExampleError.tsx
- src/components/Attach/stories/examples/AttachExampleEvents/AttachExampleEvents.tsx
- src/components/Attach/stories/examples/AttachExampleLoading/AttachExampleLoading.tsx
- src/hooks/useClickOutside.ts
- src/utils/setRef.ts
- src/utils/useForkRef.ts
closes #210
Убрал игноры где было возможно остались 
- в старом Select,
- в setRef, `ref.current = value;` = ref.current - доступен только для чтения, но нам нужно иметь возможность засетить реф, сейчас используется когда нужно указать более одной ссылки на один DOM елемент.
> fix(ts-ignore): removed ts-ignore

- build.config.js
- src/components/Tag/Tag.css
- src/components/Tag/Tag.test.tsx
- src/components/Tag/Tag.tsx
- src/components/Tag/stories/Tag.mdx
- src/components/Tag/stories/Tag.stories.tsx
- src/components/TagBase/TagBase.css
- src/components/TagBase/TagBase.test.tsx
- src/components/TagBase/TagBase.tsx
- src/utils/useTimer.ts
Добавил новый компонет Tag, создал его на TagBase.  TagBase - компонент который максимально умеет комбинировать модификаторы, Tag - в зависимости от "роли" наделяет необходимыми модификаторами TagBase и ограничевает их использование.
В зависимости от роли выводится нужный тип, прошу проверить тут получше, тут далеко не с первого раза удалось это сделать, может будут идеи как сделать лучше.
Сейчас названия ролей `'check' | 'button' | 'cancel'` думаю это не финальный вариант.
В TagBase есть стори, это сейчас для того чтобы просто посмотреть на компонент, как только все согласуем по компонету так уберу.
closes #219
> feat(Tag): add component Tag

- src/components/File/__stories__/File.stories.tsx
- src/components/FileField/__stories__/FileField.stories.tsx
- src/components/Informer/__stories__/Informer.stories.tsx
- src/components/Timer/__stories__/Timer.stories.tsx
closed  #284
* Поменял располоджение компонента FIleField
сейчас UiKit/FIleField
надо Components/FIleField
* не во всех стори был экспорт через createMetadata
> docs(StoryBook): change path FileField, export with createMetadata

- src/components/Table/Table.css
closes #303 
В полосатой таблице у строки с фоном не менялся фон при ховере
> fix(Table): even row's background wasn't changing on hover

- src/components/Combobox/__mocks__/data.mock.ts
- src/components/Combobox/__stories__/Combobox.mdx
- src/components/Combobox/__stories__/Combobox.stories.tsx
- src/components/MultiCombobox/__stories__/MultiCombobox.stories.tsx
issue -  #480
Добавил отдельное стори __c cозданием новой опции__
исправил ошибку при которой во всех стори показывалась кнопка __добавить__, но не работала
перенес массивы данных в `__mocks__`
> docs(Combobox): fixed onCreate story

- src/components/ChoiceGroup/ChoiceGroup.css
- src/components/ChoiceGroup/ChoiceGroup.tsx
- src/components/ChoiceGroup/Item/ChoiceGroup-Item.tsx
- src/components/ChoiceGroup/__stories__/ChoiceGroup.mdx
- src/components/ChoiceGroup/__stories__/ChoiceGroup.stories.tsx
- src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleMultiple/ChoiceGroupExampleMultiple.tsx
- src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleTextOverflow/ChoiceGroupExampleTextOverflow.tsx
- src/components/ChoiceGroup/__stories__/examples/ChoiceGroupExampleWidth/ChoiceGroupExampleWidth.tsx
closes #549 
Добавляет модификатор width_full, растягивающий группу кнопок на всю ширину родителя. В фигму такой модификатор тоже добавлен.
Также добавлено обрезание слишком длинного текста во всех размерах, если группа кнопок не влезает в родителя.
> feat(Choicegroup): added width_full

- src/components/Table/Table.tsx
- src/components/Table/__mock__/data.mock.tsx
- src/components/Table/__stories__/Table.mdx
- src/components/Table/__stories__/Table.stories.tsx
- src/components/Table/filtering.ts
Вынес функцию sortBy в props чтобы можно было задать свою кастомную сортировку.
Для задачи https://jira.csssr.io/browse/GDC-1050 нужна сортировка времени с датой. Думаю нет смысла держать логику сортировки в Table компоненте
> feat(components): table. Вынес sortBy в props

- src/components/Attach/Attach.tsx
- src/components/Avatar/Avatar.tsx
- src/components/Badge/Badge.tsx
- src/components/Button/Button.tsx
- src/components/TagBase/TagBase.tsx
- src/components/Text/Text.tsx
- src/components/User/User.tsx
- src/utils/types/PropsWithAsAttributes.ts
issue -  #192
теперь forwardRefWithAs возвращает верный тип, так чтоб `as` нормально отрабатывал и свойства компонента в зависимости от его тэга менялись верно
> fix(forwardRefWithAs): fixed returned type

- src/components/MultiCombobox/MultiCombobox.tsx
- src/components/MultiCombobox/__stories__/MultiCombobox.stories.tsx
issue - #470
поправил типы чтоб нормально выводился getGroupOptions
в компоненте пришлось прибегнуть к приведению типов, это вынужденная мера, чтоб не переписывать useSelect
лучше пока так оставить чем приводить к типам вне компонента
> feat: (MultiCombobox) fixed getGroupOptions types

- src/components/Sidebar/__stories__/examples/SidebarExample/SidebarExample.tsx
Поменяла ошибку в документации: пример для position = bottom открывался справа. Теперь всё ок.
> docs(sidebar): fix position bottom example

- src/components/Table/__tests__/helpers.test.ts
- src/components/Table/helpers.ts
Пофикшена ширина родительского заголовка относительно детей (https://github.com/gazprom-neft/consta-uikit/issues/553)
> fix(Table): parent width related child headers (#553)

- src/hooks/useComponentSize/useComponentSize.tsx
Хук useComponentSize не умеет работать с SVG элементами, для некоторых графиков из `@consta/widgets` это необходимо.
> feat(hooks): добавлена возможность получать размеры SVG элементов в хуке useComponentSiz

- src/components/Combobox/Combobox.tsx
- src/components/Combobox/__stories__/Combobox.docs.mdx
- src/components/Combobox/__stories__/Combobox.stories.tsx
Добавлен `inputRef` для компонента Combobox. Issue - https://github.com/gazprom-neft/consta-uikit/issues/922
> feat(Combobox): added inputRef prop

- src/components/Calendar/CalendarSlider/CalendarSlider.css
- src/components/Calendar/CalendarViewOneMonth/CalendarViewOneMonth.tsx
- src/components/Calendar/CalendarViewSlider/CalendarViewSlider.tsx
- src/components/Calendar/CalendarViewTwoMonths/CalendarViewTwoMonths.tsx
- src/components/Calendar/__stories__/Calendar.stories.tsx
- src/components/Calendar/helpers.ts
issue -  #1192
Если есть `currentVisibleDate` то открываем календарь с этим месяцем
Если есть `value` то календарь открывается на том месяце на котором есть `value`
Если есть `minDate` и `maxDate` и текущая дата не входит в этот диапазон, то открываем календарь с месяцем из `minDate` 
Если `minDate && !maxDate && currentDate < minDateTime` то `minDate`
Если `!minDate && maxDate && currentDate > minDateTime` то `maxDate`
в остальных случаях `currentDate`
> feat(Calendar): added useCurrentVisibleDate

- src/components/Informer/__stories__/Informer.docs.mdx
- src/components/Informer/__stories__/examples/InformerExampleSize/InformerExampleSize.tsx
Добавила описание модификатора size и пару примеров, поправила оглавление.
> docs(Informer): add size description in documentation

- jest.setup.ts
- src/components/BasicSelectDeprecated/__tests__/BasicSelect.test.tsx
- src/components/Combobox/__tests__/Combobox.test.tsx
- src/components/ComboboxDeprecated/__tests__/Combobox.test.tsx
- src/components/ContextMenu/__tests__/ContextMenu.test.tsx
- src/components/MultiComboboxDeprecated/__tests__/MultiCombobox.test.tsx
- src/components/Select/__tests__/Select.test.tsx
- src/components/Table/__tests__/Table.test.tsx
- src/components/Tabs/Tabs.css
- src/components/Tabs/Tabs.tsx
- src/components/ThemeToggler/__tests__/ThemeToggler.test.tsx
- src/components/UserSelect/__tests__/UserSelect.test.tsx
- src/components/UserSelectDeprecated/__tests__/UserSelect.test.tsx
- src/hocs/withTooltip/__tests__/withTooltip.test.tsx
- src/hooks/useComponentSize/useComponentSize.tsx
- src/hooks/useResizeObserved/useResizeObserved.ts
* Переписал механизм расчёта положения подчёркивания в табах с использованием ResizeObserver
* Упростил вёрстку подчёркивания
* Добавил хук useResizeObserved, который позволяет отслеживать изменение размеров сразу группы элементов
> refactor(Tabs): used ResizeObserver to detect tab width changes

- src/components/SnackBar/Item/SnackBar-Item.tsx
- src/components/SnackBar/SnackBar.tsx
- src/components/SnackBar/Timer/SnackBar-Timer.tsx
- src/components/SnackBar/__stories__/SnackBar.docs.mdx
- src/components/SnackBar/__stories__/SnackBar.stories.tsx
- src/components/SnackBar/__stories__/examples/SnackBarExampleTimer/SnackBarExampleTimer.tsx
Closes #972
- Изменено поведение по умолчанию.
По умолчанию, если указать `autoClose`, но не указывать `showProgress`, таймер будет невидимым.
Если использовать `showProgress`, то таймер будет работать без визуального отображения, а иконка будет видна, как без `autoClose`.
Если не использовать `hideTimer`, то поведение будет таким-же, как и раньше.
> # ПОСЛЕ РЕВЬЮ
> - Изменено поведение по умолчанию.
> 
> По умолчанию, если указать `autoClose`, но не указывать `showProgress`, таймер будет невидимым.
> Если указать `showProgress="timer"`, то таймер будет работать как раньше. Таймер так-же отображается вместо иконки, если включены оба.
> feat(SnackBar): Add hideTimer props

- src/components/Modal/Modal.tsx
- src/uiKit/components/DocsDecorator/DocsDecorator.tsx
- src/uiKit/components/StoryBookRootDecorator/StoryBookRootDecorator.tsx
issue - #1017
пофиксин warning modal component, сторибук в дев режиме обернут в строгий режим
> fix(Modal): added nodeRef for CssTransition component

- src/components/Table/Table.tsx
- src/components/Table/__stories__/Table.docs.mdx
- src/components/Table/__stories__/Table.stories.tsx
Closes #987
Добавил возможность указать свою функцию генерации значения которое сравнивается при объединении строк.
Исправил функцию `getTableCellProps`, т.к. в ней происходили лишние проходы цикла
> feat(Table): Add getComparisonValue function

- src/components/SnackBar/__stories__/SnackBar.stories.tsx
issue #1572
* Исправлен баг в сторибуке связанный с тем что при выключенном отображении кнопки закрытия и включенном автозакрытии элемент не пропадал.
> fix(SnackBar): fix bug with not working autoclose in playground

- src/components/Select/Select.tsx
Fix bug when placeholder showing if item is negative number or zero
closes #1758
* Исправлен баг с плэйсхолдером при выставлено значении
> fix(Select): fix bug with placeholder

- src/hooks/useSelect/useSelect.ts
Fix bug when NotFoundLabel showing if search has results
closes #1781
* Исправлен баг, когда notFoundLabel появлялся при наличии результатов
> fix(useSelect): fix bug with notFoundLabel

- README.md
- docs/common/start.stories.mdx
- docs/thematization/howToConnectTheme.stories.mdx
closes #1547
Добавлено   `import React from 'react'` во все примеры где этого не было указано
> docs(import): add import react to all missing examples

- src/components/SelectComponents/SelectDropdown/SelectDropdown.css
Remove width: 100% from Select dropdown
В основе списка используется Popover, в котором уже указывается ширина, по сему достаточно было просто удалить `width` из класса `.SelectDropdown`.
> fix(Select): fix width

- .github/workflows/deploy.yml
- src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
Если в компонент `Combobox` приходит пустой список `items`, то при поиске элемента показывался и лэйбл "Не найдено" и "Список пуск".
Для такого случая убрал `labelForNotFound` в `SelectDropdown`
> feat(Combobox): hide label for not found while items list is empty

- src/components/Header/__stories__/Header.docs.mdx
closes #2168
Поправила опечтаку в документации: Heder —> Header
> docs(Header): fix typo in doc 

- src/components/DatePicker/DatePickerFieldTypeDate/helpers.ts
- src/components/DatePicker/DatePickerFieldTypeDateTime/helpers.ts
- src/components/DatePicker/DatePickerFieldTypeMonth/helpers.ts
- src/components/DatePicker/DatePickerFieldTypeTime/helpers.ts
- src/components/DatePicker/DatePickerFieldTypeYear/helpers.ts
- src/components/DatePicker/helpers.ts
fix #2979
Нелзя было использовать формат без полного набора групп
К примеру:
рекомендуется `HH:mm:ss` и не возможно испорлзовать `HH:mm`
рекомендуется `dd:MM:yyyy` и не возможно испорлзовать `dd:MM`
Данный фикс исправляет эту проблему
> fix(DatePicker): fixed validate mask

- package.json
- src/components/AutoCompleteCanary/AutoCompleteCanary.tsx
- src/components/AutoCompleteCanary/__stand__/AutoComplete.dev.stand.mdx
- src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleDropdownOpen/AutoCompleteExampleDropdownOpen.tsx
- src/components/AutoCompleteCanary/types.ts
- src/components/AutoCompleteCanary/useAutoComplete.ts
- src/components/ComboboxCanary/ComboboxCanary.tsx
- src/components/ComboboxCanary/__stand__/Combobox.dev.stand.mdx
- src/components/ComboboxCanary/__stand__/examples/ComboboxExampleDropdownOpen/ComboboxExampleDropdownOpen.tsx
- src/components/ComboboxCanary/__stand__/examples/ComboboxExampleIsLoading/ComboboxExampleIsLoading.tsx
- src/components/ComboboxCanary/helpers.ts
- src/components/SelectCanary/SelectCanary.tsx
- src/components/SelectCanary/__stand__/Select.dev.stand.mdx
- src/components/SelectCanary/__stand__/examples/SelectExampleDropdownOpen/SelectExampleDropdownOpen.tsx
- src/components/SelectCanary/__stand__/examples/SelectExampleIsLoading/SelectExampleIsLoading.tsx
- src/components/SelectCanary/helpers.ts
- src/components/SelectComponentsCanary/useSelect/useSelect.ts
- src/components/UserSelectCanary/UserSelectCanary.tsx
- src/components/UserSelectCanary/__stand__/UserSelect.dev.stand.mdx
- src/components/UserSelectCanary/__stand__/examples/UserSelectExampleDropdownOpen/UserSelectExampleDropdownOpen.tsx
- src/components/UserSelectCanary/__stand__/examples/UserSelectExampleIsLoading/UserSelectExampleIsLoading.tsx
- src/components/UserSelectCanary/helpers.ts
- src/hooks/useFlag/useFlag.ts
- src/icons/createIcon/createIcon.tsx
- yarn.lock
Добавили свойства для управления выподающего списка:
1) dropdownOpen
2) dropdownOnOpen
3) ignoreOutsideClicksRefs
Доработали управление с клавиатуры:
По фокусу на поле ввода список не должен открываться, подсвечивается поле
При фокусе и закрытом списке по Enter, список открывается
При фокусе и закрытом списке по нажатию стрелочек вверх и вниз список открывается
При фокусе и открытом списке по нажатию Esc список должен закрываться
При фокусе и закрытом списке по нажатию Tab список должен закрываться, и фокус должен оставаться на поле ввода
closed #3090
> feat(Selects): add props for control dropdown open/close state

- src/components/ListCanary/ListItem/ListItem.tsx
Fixed problem that causes Combobox, ContextMenu, Select list items to have wrong text/icon colors with dark theme by adding default value to status property;
fix #3317
Добавил дефолтное значение для пропсы status компоненту ListItem у ListCanary, что бы при не заданном свойстве для текста подставлялся css класс `Text_view_primary` по-умолчанию
> fix(List): fixed dafault color of list items in dark theme

- src/components/Table/TextFilter/TableTextFilter.tsx
- src/components/Table/__tests__/Table.test.tsx
Пользовательский ввод не проверялся и записывался в регулярное выражение без предобработки. 
Со сторы регулярки * первым символом выглядело как: повтори предыдущий(отсутствующий) символ сколько угодно раз, и так далее.
Теперь ввод экранируется
Написан тест для проверки экранирования
fixes #3654
> fix(Table): Добавлена предобработка пользовательского ввода

- src/components/Tooltip/Tooltip.tsx
Есть не передан nodeRef, Transition из react-transition-group делает fallback на deprecated React API (findDOMNode(this)), то есть пытается получить своих children-ов
fixes #3668
> fix(tootip): Добавлен проброс ref в Transition

- src/components/Table/TextFilter/TableTextFilter.tsx
- src/components/Table/__tests__/Table.test.tsx
fixes #3656
- переработана фильтрация: теперь фильтр отрабатывает по видимым чекбоксам, а не по всем
- соответственно и кнопки выбрать все и сбросить привязаны к видимым чекбоксам
- написаны тесты
- вынесено конструирование регулярного выражения: теперь оно создается 1 раз за ввод, а не на каждый элемент
> fix(table-filter): Apply filter based on visible and checked elements

- src/components/FieldComponents/FieldArrayValueInlineControl/FieldArrayValueInlineControl.tsx
- src/components/FieldComponents/FieldArrayValueInlineControl/types.ts
- src/components/TextField/TextField.tsx
- src/components/TextField/__tests__/TextField.test.tsx
- src/components/TextFieldCanary/TextFieldTypeNumber/TextFieldTypeNumber.tsx
- src/components/TextFieldCanary/TextFieldTypePassword/TextFieldTypePassword.tsx
- src/components/TextFieldCanary/TextFieldTypeText/TextFieldTypeText.tsx
- src/components/TextFieldCanary/TextFieldTypeTextArea/TextFieldTypeTextArea.tsx
- src/components/TextFieldCanary/TextFieldTypeTextArray/TextFieldTypeTextArray.tsx
- src/components/TextFieldCanary/types.ts
- yarn.lock
Закрывает #3767. Добавил патч на слушатель события `wheel`. Добавил тесты.
> feat(TextField): add wheel event handler for input[type="number"]

- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/__stand__/Tooltip.dev.stand.mdx
- src/components/Tooltip/types.ts
closes #3899. Прокинул проп `container` из `Tooltip` в `Popover`
> feat(Tooltip): adds container prop

- src/components/UserSelect/UserSelect.tsx
- src/components/UserSelect/UserSelectValue/UserSelectValue.css
При использовании UserSelect вместе с полными именами вне зависимости от размера контейнера имя обрезается, так же вне зависимости от использования multiply свойства Select всегда использует multiply
До исправлений
После исправлений
> fix(UserSelect): исправление обрезания ФИО значения
